using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows.Forms;

namespace ArtifactManagerModern {
  sealed class ArtifactRow {
    public string Artefact{get;set;} public string Obtained{get;set;} public string Categorie{get;set;} public string Restriction{get;set;} public string Rarete{get;set;} public int Niveau{get;set;} public string StatPrincipale{get;set;} public string Stat1{get;set;} public string Stat2{get;set;} public string Stat3{get;set;} public string Stat4{get;set;} public string Action{get;set;} public double Potential{get;set;} public string Conversion{get;set;} public string Preset{get;set;} public string Mode{get;set;} public string EquipeSur{get;set;} public string Verrouille{get;set;} public long Rid{get;set;} public double ReappPriority{get;set;} public string ReappReason{get;set;} public double RetentionThreshold{get;set;} public string BestMonster{get;set;} public double ReappGain{get{return ReappPriority-Potential;}} public DateTime ObtainedDate{get{DateTime value;return DateTime.TryParseExact(Obtained,"yyyy-MM-dd HH:mm:ss",CultureInfo.InvariantCulture,DateTimeStyles.None,out value)?value:DateTime.MinValue;}}
  }
  sealed class ArtifactReappraisalComparison {
    public ArtifactRow Before,After;
    public bool TakeAfter{get{return After!=null&&Before!=null&&After.Potential>Before.Potential;}}
  }
  sealed class MonsterOption { public int Id;public string Name,Family,Element,ImagePath;public override string ToString(){return Name??"";} }
  sealed class BufferedGrid:DataGridView { public BufferedGrid(){DoubleBuffered=true;} }
  static class Program {
    [STAThread] static void Main(string[] args){if(args.Length>1&&args[0]=="--self-test"){var rows=EngineBridge.Run(args[1],"");Console.WriteLine("ARTIFACTS="+rows.Count+" KEEP="+rows.Count(x=>x.Action=="Keep")+" SELL="+rows.Count(x=>x.Action=="Sell")+" TOP="+(rows.Count==0?0:rows.Max(x=>x.Potential)).ToString("0.000",CultureInfo.InvariantCulture)+" CORE_FRAGMENTS="+EngineBridge.ReadCoreFragments(args[1]));return;}if(args.Length>2&&args[0]=="--self-test-reapp"){var comparison=EngineBridge.CompareReappraisal(args[1],new List<string>(),File.ReadAllText(args[2],Encoding.UTF8));Console.WriteLine(comparison==null?"REAPP=NULL":"REAPP=OK RID="+comparison.Before.Rid+" BEFORE="+comparison.Before.Potential.ToString("0.000",CultureInfo.InvariantCulture)+" AFTER="+comparison.After.Potential.ToString("0.000",CultureInfo.InvariantCulture));return;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new MainForm());}
  }
  static class EngineBridge {
    public static int RetentionLimit=1500;
    public static bool FixedMode=false;
    public static double FixedValue=8.8;
    public static int ReadCoreFragments(string json){try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var root=js.DeserializeObject(File.ReadAllText(json,Encoding.UTF8)) as Dictionary<string,object>;object raw;if(root!=null&&root.TryGetValue("inventory_info",out raw))foreach(var item in raw as object[]??new object[0]){var d=item as Dictionary<string,object>;if(d==null)continue;object t,id,q;if(d.TryGetValue("item_master_type",out t)&&d.TryGetValue("item_master_id",out id)&&d.TryGetValue("item_quantity",out q)&&Convert.ToInt32(t)==75&&Convert.ToInt32(id)==2)return Math.Max(0,Convert.ToInt32(q));}}catch{}return 0;}
    public static List<ArtifactRow> Run(string json,string filter,string category="",string mode="",IList<string> liveEvents=null,IEnumerable<string> priorityMonsters=null,IEnumerable<long> reappTargets=null,IEnumerable<long> excludedArtifacts=null){
      string root=AppDomain.CurrentDomain.BaseDirectory,engine=Path.Combine(root,"ArtifactManagerEngine.exe"),data=Path.Combine(root,"Artifact_Manager_Data.json"),temp=Path.Combine(Path.GetTempPath(),"artifact_app_"+Guid.NewGuid().ToString("N")+".tsv"),priorityFile=Path.Combine(Path.GetTempPath(),"artifact_priority_"+Guid.NewGuid().ToString("N")+".txt"),targetFile=Path.Combine(Path.GetTempPath(),"artifact_targets_"+Guid.NewGuid().ToString("N")+".txt"),merged="";if(!File.Exists(engine)||!File.Exists(data))throw new FileNotFoundException("Le moteur ou sa base de données est absent du dossier de l’application.");string input=json;var excluded=new HashSet<long>(excludedArtifacts??Enumerable.Empty<long>());if((liveEvents!=null&&liveEvents.Count>0)||excluded.Count>0){merged=BuildMergedJson(json,liveEvents,excluded);if(merged.Length>0)input=merged;}File.WriteAllLines(priorityFile,priorityMonsters??Enumerable.Empty<string>(),Encoding.UTF8);File.WriteAllLines(targetFile,(reappTargets??Enumerable.Empty<long>()).Select(x=>x.ToString(CultureInfo.InvariantCulture)),Encoding.UTF8);
      var psi=new ProcessStartInfo(engine){UseShellExecute=false,CreateNoWindow=true,WindowStyle=ProcessWindowStyle.Hidden};psi.Arguments=Q(input)+" "+Q(data)+" "+Q(temp)+" "+Q(filter??"")+" "+Q(category??"")+" "+Q(mode??"")+" "+Q(priorityFile)+" "+Q(targetFile)+" "+RetentionLimit.ToString(CultureInfo.InvariantCulture)+" "+(FixedMode?"fixed":"count")+" "+FixedValue.ToString(CultureInfo.InvariantCulture);using(var p=Process.Start(psi)){p.WaitForExit();if(p.ExitCode!=0)throw new Exception("Le moteur d’analyse a renvoyé l’erreur "+p.ExitCode+".");}
      var result=new List<ArtifactRow>();try{foreach(string line in File.ReadAllLines(temp,Encoding.UTF8)){if(string.IsNullOrWhiteSpace(line))continue;var c=line.Split(new[]{'\t'});if(c.Length<19)continue;double potential,reappPriority=0,retentionThreshold=0;long rid;int level;double.TryParse(c[12],NumberStyles.Any,CultureInfo.InvariantCulture,out potential);if(c.Length>19)double.TryParse(c[19],NumberStyles.Any,CultureInfo.InvariantCulture,out reappPriority);if(c.Length>21)double.TryParse(c[21],NumberStyles.Any,CultureInfo.InvariantCulture,out retentionThreshold);long.TryParse(c[18],out rid);int.TryParse(c[5],out level);result.Add(new ArtifactRow{Artefact=c[0],Obtained=c[1],Categorie=c[2],Restriction=c[3],Rarete=c[4],Niveau=level,StatPrincipale=c[6],Stat1=c[7],Stat2=c[8],Stat3=c[9],Stat4=c[10],Action=c[11],Potential=potential,Conversion=c[13],Preset=c[14],Mode=c[15],EquipeSur=c[16],Verrouille=c[17],Rid=rid,ReappPriority=reappPriority,ReappReason=c.Length>20?c[20]:"",RetentionThreshold=retentionThreshold,BestMonster=c.Length>22?c[22]:""});}}finally{try{File.Delete(temp);}catch{}try{File.Delete(priorityFile);}catch{}try{File.Delete(targetFile);}catch{}try{if(merged.Length>0)File.Delete(merged);}catch{}}return result;
    }
    public static List<long> ArtifactIds(string json){var result=new List<long>();try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var found=new Dictionary<string,Dictionary<string,object>>();CollectArtifacts(js.DeserializeObject(json),found);foreach(var key in found.Keys){long id;if(long.TryParse(key,out id)&&id>0)result.Add(id);}}catch{}return result;}
    public static List<long> SoldArtifactIds(string json){var result=new List<long>();try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var root=js.DeserializeObject(json) as Dictionary<string,object>;object command,ids,ret;if(root==null||!root.TryGetValue("command",out command)||!string.Equals(Convert.ToString(command),"SellArtifacts",StringComparison.OrdinalIgnoreCase)||(root.TryGetValue("ret_code",out ret)&&Convert.ToInt32(ret)!=0)||!root.TryGetValue("artifact_ids",out ids))return result;foreach(var raw in ids as object[]??new object[0]){long id;if(long.TryParse(Convert.ToString(raw),out id)&&id>0)result.Add(id);}}catch{}return result;}
    public static ArtifactReappraisalComparison CompareReappraisal(string json,IList<string> liveEvents,string response){
      try{
        var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var root=js.DeserializeObject(response) as Dictionary<string,object>;object raw;if(root==null||!root.TryGetValue("command",out raw)||!IsReappraisalCommand(Convert.ToString(raw)))return null;if(root.TryGetValue("ret_code",out raw)&&Convert.ToInt32(raw)!=0)return null;
        object beforeRaw,afterRaw;var beforeArtifact=root.TryGetValue("artifact_before",out beforeRaw)?beforeRaw as Dictionary<string,object>:null;var afterArtifact=root.TryGetValue("artifact_after",out afterRaw)?afterRaw as Dictionary<string,object>:null;
        if(beforeArtifact!=null&&afterArtifact!=null){object ridRaw;if(!beforeArtifact.TryGetValue("rid",out ridRaw))return null;long rid;if(!long.TryParse(Convert.ToString(ridRaw),out rid)||rid<=0)return null;var beforeEvents=new List<string>();if(liveEvents!=null)beforeEvents.AddRange(liveEvents);beforeEvents.Add(js.Serialize(new Dictionary<string,object>{{"command","ArtifactReappraisalPreviewBefore"},{"artifact",beforeArtifact}}));var afterEvents=new List<string>();if(liveEvents!=null)afterEvents.AddRange(liveEvents);afterEvents.Add(js.Serialize(new Dictionary<string,object>{{"command","ArtifactReappraisalPreviewAfter"},{"artifact",afterArtifact}}));var before=Run(json,"","","",beforeEvents).FirstOrDefault(x=>x.Rid==rid);var after=Run(json,"","","",afterEvents).FirstOrDefault(x=>x.Rid==rid);return before!=null&&after!=null?new ArtifactReappraisalComparison{Before=before,After=after}:null;}
        var candidates=new Dictionary<string,Dictionary<string,object>>();CollectArtifacts(root,candidates);if(candidates.Count==0)return null;var beforeRows=Run(json,"","","",liveEvents);var ids=new HashSet<long>(candidates.Keys.Select(x=>{long id;return long.TryParse(x,out id)?id:0;}));var previous=beforeRows.FirstOrDefault(x=>ids.Contains(x.Rid));if(previous==null)return null;var events=new List<string>();if(liveEvents!=null)events.AddRange(liveEvents);events.Add(response);var next=Run(json,"","","",events).FirstOrDefault(x=>x.Rid==previous.Rid);return next!=null?new ArtifactReappraisalComparison{Before=previous,After=next}:null;
      }catch{return null;}
    }
    public static bool IsReappraisalCommand(string command){return string.Equals(command,"convertArtifactByCoreFragment",StringComparison.OrdinalIgnoreCase)||(command.IndexOf("Artifact",StringComparison.OrdinalIgnoreCase)>=0&&(command.IndexOf("Revalue",StringComparison.OrdinalIgnoreCase)>=0||command.IndexOf("Reapp",StringComparison.OrdinalIgnoreCase)>=0));}
    static string BuildMergedJson(string json,IList<string> events,HashSet<long> excluded){var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var game=js.DeserializeObject(File.ReadAllText(json,Encoding.UTF8)) as Dictionary<string,object>;var updates=new Dictionary<string,Dictionary<string,object>>();var unitUpdates=new Dictionary<string,Dictionary<string,object>>();foreach(string line in events??new string[0]){try{var parsed=js.DeserializeObject(line);var root=parsed as Dictionary<string,object>;object command,ids,ret;bool sale=root!=null&&root.TryGetValue("command",out command)&&string.Equals(Convert.ToString(command),"SellArtifacts",StringComparison.OrdinalIgnoreCase)&&(!root.TryGetValue("ret_code",out ret)||Convert.ToInt32(ret)==0);if(sale&&root.TryGetValue("artifact_ids",out ids)){foreach(var id in ids as object[]??new object[0]){long value;if(long.TryParse(Convert.ToString(id),out value))excluded.Add(value);}continue;}CollectArtifacts(parsed,updates);CollectUnits(parsed,unitUpdates);}catch{}}if(updates.Count==0&&unitUpdates.Count==0&&excluded.Count==0)return "";foreach(long id in excluded)updates.Remove(id.ToString());ReplaceArtifacts(game,updates);object raw;var list=new List<object>();if(game.TryGetValue("artifacts",out raw))list.AddRange((raw as object[]??new object[0]).Where(x=>{var d=x as Dictionary<string,object>;object id;long value;return d==null||!d.TryGetValue("rid",out id)||!long.TryParse(Convert.ToString(id),out value)||!excluded.Contains(value);}));var present=new HashSet<string>(list.Select(x=>{var d=x as Dictionary<string,object>;object id;return d!=null&&d.TryGetValue("rid",out id)?Convert.ToString(id):"";}));foreach(var kv in updates)if(!present.Contains(kv.Key))list.Add(kv.Value);game["artifacts"]=list.ToArray();var units=new List<object>();if(game.TryGetValue("unit_list",out raw))units.AddRange(raw as object[]??new object[0]);var unitIndex=new Dictionary<string,int>();for(int i=0;i<units.Count;i++){var d=units[i] as Dictionary<string,object>;object id;if(d!=null&&d.TryGetValue("unit_id",out id))unitIndex[Convert.ToString(id)]=i;}foreach(var kv in unitUpdates){int i;if(unitIndex.TryGetValue(kv.Key,out i))units[i]=kv.Value;else units.Add(kv.Value);}foreach(var item in units){var u=item as Dictionary<string,object>;if(u==null||!u.TryGetValue("artifacts",out raw))continue;u["artifacts"]=(raw as object[]??new object[0]).Where(x=>{var d=x as Dictionary<string,object>;object id;long value;return d==null||!d.TryGetValue("rid",out id)||!long.TryParse(Convert.ToString(id),out value)||!excluded.Contains(value);}).ToArray();}game["unit_list"]=units.ToArray();string path=Path.Combine(Path.GetTempPath(),"artifact_live_"+Guid.NewGuid().ToString("N")+".json");File.WriteAllText(path,js.Serialize(game),Encoding.UTF8);return path;}
    static void CollectArtifacts(object value,Dictionary<string,Dictionary<string,object>> found){var d=value as Dictionary<string,object>;if(d!=null){object rid;if(d.TryGetValue("rid",out rid)&&d.ContainsKey("pri_effect")&&d.ContainsKey("sec_effects")&&d.ContainsKey("type")){string id=Convert.ToString(rid);if(id.Length>0&&id!="0")found[id]=d;return;}foreach(var kv in d)CollectArtifacts(kv.Value,found);return;}foreach(var x in value as object[]??new object[0])CollectArtifacts(x,found);}
    static void CollectUnits(object value,Dictionary<string,Dictionary<string,object>> found){var d=value as Dictionary<string,object>;if(d!=null){object uid,mid;if(d.TryGetValue("unit_id",out uid)&&d.TryGetValue("unit_master_id",out mid)&&d.ContainsKey("skills")){string id=Convert.ToString(uid);if(id.Length>0&&id!="0")found[id]=d;return;}foreach(var kv in d)CollectUnits(kv.Value,found);return;}foreach(var x in value as object[]??new object[0])CollectUnits(x,found);}
    static void ReplaceArtifacts(object value,Dictionary<string,Dictionary<string,object>> updates){var d=value as Dictionary<string,object>;if(d!=null){foreach(var key in d.Keys.ToList()){var child=d[key] as Dictionary<string,object>;object rid;if(child!=null&&child.TryGetValue("rid",out rid)&&updates.ContainsKey(Convert.ToString(rid)))d[key]=updates[Convert.ToString(rid)];else ReplaceArtifacts(d[key],updates);}return;}var a=value as object[];if(a==null)return;for(int i=0;i<a.Length;i++){var child=a[i] as Dictionary<string,object>;object rid;if(child!=null&&child.TryGetValue("rid",out rid)&&updates.ContainsKey(Convert.ToString(rid)))a[i]=updates[Convert.ToString(rid)];else ReplaceArtifacts(a[i],updates);}}
    static string Q(string s){return "\""+s.Replace("\"","\\\"")+"\"";}
  }
  sealed class MainForm:Form {
    static readonly Color Bg=Color.FromArgb(5,14,24),Panel=Color.FromArgb(12,29,43),Teal=Color.FromArgb(18,137,128),Cyan=Color.FromArgb(8,145,178);
    readonly BufferedGrid grid=new BufferedGrid();readonly Label status=new Label(),summary=new Label();readonly TextBox search=new TextBox();readonly ComboBox category=new ComboBox(),restriction=new ComboBox(),action=new ComboBox(),preset=new ComboBox(),monster=new ComboBox();readonly Dictionary<string,Image> artifactIcons=new Dictionary<string,Image>(StringComparer.OrdinalIgnoreCase),monsterImages=new Dictionary<string,Image>(StringComparer.OrdinalIgnoreCase);readonly List<MonsterOption> monsterOptions=new List<MonsterOption>();readonly Dictionary<string,string> monsterIconByName=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);readonly HashSet<string> priorityMonsters=new HashSet<string>(StringComparer.OrdinalIgnoreCase);readonly HashSet<long> reappTargets=new HashSet<long>(),soldArtifactIds=new HashSet<long>();readonly Timer jsonDebounce=new Timer(),liveLogTimer=new Timer();readonly List<string> liveEvents=new List<string>();FileSystemWatcher jsonWatcher;Button reappButton,priorityButton,retentionButton;int retentionButtonLeft=14;List<ArtifactRow> all=new List<ArtifactRow>();string currentJson="",viewMode="potential",pendingJson="",liveLogPath="",liveLogPending="";long liveLogOffset=0;bool obtainedSort=false,liveAwaitingResponse=false,importing=false,liveCoreKnown=false,filteringMonsters=false,fixedSellThreshold=LoadInitialFixedMode();int coreFragments=0,retentionLimit=LoadInitialRetentionLimit();double fixedSellThresholdValue=LoadInitialFixedValue();
    static int LoadInitialRetentionLimit(){int value=1500;try{string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ArtifactManagerModern"),path=Path.Combine(dir,"retention_limit.txt"),raw=File.Exists(path)?File.ReadAllText(path).Trim():"";int parsed;if(int.TryParse(raw,out parsed))value=Math.Max(100,Math.Min(10000,parsed));}catch{}EngineBridge.RetentionLimit=value;return value;}
    static bool LoadInitialFixedMode(){bool value=false;try{string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ArtifactManagerModern"),path=Path.Combine(dir,"sell_threshold_mode.txt");if(File.Exists(path))value=File.ReadAllText(path).Trim().Equals("fixed",StringComparison.OrdinalIgnoreCase);}catch{}EngineBridge.FixedMode=value;return value;}
    static double LoadInitialFixedValue(){double value=8.8;try{string dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ArtifactManagerModern"),path=Path.Combine(dir,"sell_threshold_fixed_value.txt"),raw=File.Exists(path)?File.ReadAllText(path).Trim():"";double parsed;if(double.TryParse(raw,NumberStyles.Any,CultureInfo.InvariantCulture,out parsed))value=Math.Max(0,parsed);}catch{}EngineBridge.FixedValue=value;return value;}
    public MainForm(){Text="Artifact Manager — Application";WindowState=FormWindowState.Maximized;MinimumSize=new Size(1150,680);BackColor=Bg;ForeColor=Color.White;Font=new Font("Segoe UI",10);LoadArtifactIcons();LoadReappSettings();Build();jsonDebounce.Interval=1000;jsonDebounce.Tick+=(s,e)=>{jsonDebounce.Stop();if(File.Exists(pendingJson)){currentJson=pendingJson;liveEvents.Clear();liveCoreKnown=false;ImportCurrent(true);}};liveLogTimer.Interval=500;liveLogTimer.Tick+=(s,e)=>ReadLiveLog();Shown+=(s,e)=>StartRealtime();FormClosed+=(s,e)=>{if(jsonWatcher!=null)jsonWatcher.Dispose();foreach(var image in artifactIcons.Values.Concat(monsterImages.Values))image.Dispose();};LoadLastJson();}
    // Style "fantome" repris de Rune Manager (idee de Jeremy) : plus de fond de couleur
    // pleine — fond sombre commun + contour colore (parametre color), avec une legere
    // surbrillance teintee au survol/clic. AutoSize (w sert de largeur MINIMALE, 0 = aucune)
    // + positionnement en curseur (x cumule via .Right+gap) au lieu de coordonnees figees,
    // pour eviter tout chevauchement si le texte est plus long/court que prevu a l'origine.
    static readonly Color GhostFill=Color.FromArgb(22,34,50),ComboBg=Color.FromArgb(22,34,50),LegendaryOrange=Color.FromArgb(255,170,40),EpicPurple=Color.FromArgb(150,90,230);
    Button Btn(string text,int x,int y,int w,Color color){var b=new Button{Text=text,AutoSize=true,AutoSizeMode=AutoSizeMode.GrowAndShrink,MinimumSize=new Size(w,32),Padding=new Padding(16,0,16,0),Location=new Point(x,y),FlatStyle=FlatStyle.Flat,BackColor=GhostFill,ForeColor=Color.Gainsboro,Font=new Font("Segoe UI Semibold",9),Cursor=Cursors.Hand,TextAlign=ContentAlignment.MiddleCenter};b.FlatAppearance.BorderSize=2;b.FlatAppearance.BorderColor=color;b.FlatAppearance.MouseOverBackColor=Color.FromArgb(55,color.R,color.G,color.B);b.FlatAppearance.MouseDownBackColor=Color.FromArgb(90,color.R,color.G,color.B);return b;}
    void Build(){var top=new Panel{Dock=DockStyle.Top,Height=155,BackColor=Panel};Controls.Add(top);int gap=8,x=14;
      var import=Btn("IMPORTER JSON",x,14,0,Cyan);import.Click+=(s,e)=>ChooseJson();top.Controls.Add(import);x=import.Right+gap;
      var potential=Btn("TRI POTENTIAL VALUE",x,14,0,LegendaryOrange);potential.Click+=(s,e)=>ShowFullList(false);top.Controls.Add(potential);x=potential.Right+gap;
      var obtained=Btn("TRI OBTAINED",x,14,0,LegendaryOrange);obtained.Click+=(s,e)=>ShowFullList(true);top.Controls.Add(obtained);x=obtained.Right+gap;
      var recalc=Btn("RECALCULER",x,14,0,LegendaryOrange);recalc.Click+=(s,e)=>ImportCurrent();top.Controls.Add(recalc);x=recalc.Right+gap;
      search.SetBounds(x,15,250,30);search.BackColor=GhostFill;search.ForeColor=Color.White;search.BorderStyle=BorderStyle.FixedSingle;search.TextChanged+=(s,e)=>RefreshGrid();top.Controls.Add(search);x=search.Right+gap;
      // Meme technique que les pierres de reeval dans l'appli Rune Manager : icone PAS geree
      // par Button.Image (ca forcait le bouton a grossir pour la contenir, rejete par
      // Jeremy) mais par un PictureBox enfant, positionne/dimensionne a la main, sans
      // influence sur l'AutoSize du bouton. Padding.Left du bouton reserve la place pour
      // l'icone ; le texte reste centre dans le reste de l'espace.
      reappButton=Btn("x0   REAPPRAISAL",x,14,0,LegendaryOrange);reappButton.Padding=new Padding(38,0,16,0);reappButton.TextAlign=ContentAlignment.MiddleCenter;
      reappButton.Click+=(s,e)=>ShowGlobalReappraisal();new ToolTip().SetToolTip(reappButton,"Total de Core Fragments — 10 fragments par Reappraisal");top.Controls.Add(reappButton);
      var reappIcon=new PictureBox{Image=LoadUiImageHQ("core-fragment-clean.png",28,28),SizeMode=PictureBoxSizeMode.AutoSize,BackColor=Color.Transparent,Location=new Point(9,2)};reappButton.Controls.Add(reappIcon);reappIcon.BringToFront();
      // Le calcul AutoSize (PreferredSize) d'un Button avec Image+Text n'est pas toujours
      // a jour tant que le controle n'a pas ete mesure explicitement — forcer Size=
      // PreferredSize ici evite un .Right premature (trop grand) qui laissait un ecart
      // visible avant le bouton suivant.
      // Hauteur du bouton figee = meme que les boutons voisins sans icone ("import", 32px)
      // pour ne pas grossir tout le bouton — la largeur suit le PreferredSize (texte+padding
      // reserve pour l'icone), la hauteur reste fixe.
      reappButton.Size=new Size(reappButton.PreferredSize.Width,import.Height);x=reappButton.Right+gap;
      priorityButton=Btn("MONSTRES REAPP : "+priorityMonsters.Count,x,14,0,EpicPurple);priorityButton.Click+=(s,e)=>ShowPriorityMonsters();top.Controls.Add(priorityButton);
      int y2=58;x=14;
      SetupCombo(category,x,y2,150,new[]{"Toutes catégories","Element","Type"});x+=158;SetupCombo(restriction,x,y2,170,new[]{"Toutes restrictions"});x+=178;SetupCombo(action,x,y2,125,new[]{"Toutes actions","Keep","Sell"});x+=133;SetupCombo(preset,x,y2,190,new[]{"Tous les presets"});x+=198;
      monster.SetBounds(x,y2-1,230,30);monster.DropDownStyle=ComboBoxStyle.DropDown;monster.AutoCompleteMode=AutoCompleteMode.None;monster.FlatStyle=FlatStyle.Flat;monster.BackColor=ComboBg;monster.ForeColor=Color.White;monster.DrawMode=DrawMode.OwnerDrawFixed;monster.ItemHeight=42;monster.DropDownHeight=170;monster.DropDownWidth=280;monster.MaxDropDownItems=4;monster.DrawItem+=DrawMonsterItem;monster.TextUpdate+=(s,e)=>FilterMonsterChoices();top.Controls.Add(monster);x=monster.Right+gap;
      Button er=Btn("ÉLÉMENT RTA",x,y2,0,EpicPurple);er.Click+=(s,e)=>MonsterView("Element","RTA");top.Controls.Add(er);x=er.Right+gap;
      Button es=Btn("ÉLÉMENT SIÈGE",x,y2,0,EpicPurple);es.Click+=(s,e)=>MonsterView("Element","Siege");top.Controls.Add(es);x=es.Right+gap;
      Button tr=Btn("TYPE RTA",x,y2,0,EpicPurple);tr.Click+=(s,e)=>MonsterView("Type","RTA");top.Controls.Add(tr);x=tr.Right+gap;
      Button ts=Btn("TYPE SIÈGE",x,y2,0,EpicPurple);ts.Click+=(s,e)=>MonsterView("Type","Siege");top.Controls.Add(ts);
      // Demande Jeremy : SEUIL sous le bouton ÉLÉMENT RTA (plus a droite loin de tout).
      // Position X fixe = celle d'ÉLÉMENT RTA (er.Left), retenue dans un champ car Build()
      // est la seule methode a avoir acces a la variable locale "er" — PlaceRetentionButton
      // (appelee depuis RefreshRetentionButton) doit pouvoir la reutiliser plus tard.
      retentionButtonLeft=er.Left;
      retentionButton=Btn("",retentionButtonLeft,98,0,LegendaryOrange);retentionButton.Click+=(s,e)=>ShowRetentionSettings();top.Controls.Add(retentionButton);RefreshRetentionButton();
      grid.DataBindingComplete+=(s,e)=>RefreshRetentionButton();
      summary.SetBounds(14,103,1140,24);summary.ForeColor=Color.FromArgb(116,235,184);summary.Font=new Font("Segoe UI Semibold",10);top.Controls.Add(summary);status.SetBounds(14,130,1400,22);status.ForeColor=Color.FromArgb(175,188,203);top.Controls.Add(status);
      grid.Dock=DockStyle.Fill;grid.BackgroundColor=Bg;grid.BorderStyle=BorderStyle.None;grid.GridColor=Color.FromArgb(52,72,89);grid.CellBorderStyle=DataGridViewCellBorderStyle.Single;grid.RowHeadersVisible=false;grid.ReadOnly=true;grid.AllowUserToAddRows=false;grid.SelectionMode=DataGridViewSelectionMode.CellSelect;grid.RowTemplate.MinimumHeight=98;grid.AutoSizeRowsMode=DataGridViewAutoSizeRowsMode.DisplayedCellsExceptHeaders;grid.EnableHeadersVisualStyles=false;grid.ColumnHeadersHeight=60;grid.ColumnHeadersDefaultCellStyle=new DataGridViewCellStyle{BackColor=Teal,ForeColor=Color.White,Font=new Font("Segoe UI Semibold",15),SelectionBackColor=Teal,WrapMode=DataGridViewTriState.True};grid.DefaultCellStyle=new DataGridViewCellStyle{BackColor=Bg,ForeColor=Color.White,SelectionBackColor=Color.FromArgb(26,70,83),SelectionForeColor=Color.White,Font=new Font("Segoe UI",15),Padding=new Padding(5,4,5,4),WrapMode=DataGridViewTriState.False};grid.AutoGenerateColumns=false;AddColumns();foreach(var wc in new[]{"Stat1","Stat2","Stat3","Stat4","Conversion"})grid.Columns[wc].DefaultCellStyle.WrapMode=DataGridViewTriState.True;grid.CellFormatting+=FormatCell;grid.CellPainting+=PaintArtifactIcon;Controls.Add(grid);grid.BringToFront();
    }
    void RefreshRetentionButton(){if(retentionButton!=null){double threshold=all.Count==0?0:all.Max(x=>x.RetentionThreshold);retentionButton.Text=fixedSellThreshold?"SEUIL FIXE  •  "+fixedSellThresholdValue.ToString("0.000"):"SEUIL DYNAMIQUE  "+retentionLimit.ToString("N0")+"  •  "+threshold.ToString("0.000");PlaceRetentionButton();}}
    // Position X fixe (sous ÉLÉMENT RTA, voir Build()). Le texte change de largeur a l'usage
    // mais la position reste alignee a gauche sous le bouton — pas de recalcul a droite ici.
    void PlaceRetentionButton(){if(retentionButton==null)return;retentionButton.Left=retentionButtonLeft;}
    double PreviewRetentionThreshold(int limit){var scores=all.Where(x=>x.Action!="Cible Reappraisal").Select(x=>x.Potential).OrderByDescending(x=>x).ToList();return scores.Count==0?0:scores[Math.Min(scores.Count-1,Math.Max(1,limit)-1)];}
    void SaveRetentionLimit(){try{Directory.CreateDirectory(SettingsDir);File.WriteAllText(Path.Combine(SettingsDir,"retention_limit.txt"),retentionLimit.ToString(CultureInfo.InvariantCulture));}catch{}}
    void SaveSellThresholdSettings(){try{Directory.CreateDirectory(SettingsDir);File.WriteAllText(Path.Combine(SettingsDir,"sell_threshold_mode.txt"),fixedSellThreshold?"fixed":"count");File.WriteAllText(Path.Combine(SettingsDir,"sell_threshold_fixed_value.txt"),fixedSellThresholdValue.ToString(CultureInfo.InvariantCulture));}catch{}}
    void ShowRetentionSettings(){var f=new Form{Text="Seuil des artefacts",BackColor=Bg,ForeColor=Color.White,ClientSize=new Size(470,300),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,StartPosition=FormStartPosition.CenterParent};var fixedBox=new CheckBox{Text="Seuil de vente fixe (au lieu d’un quota)",AutoSize=true,Location=new Point(28,20),Checked=fixedSellThreshold,ForeColor=Color.White,Font=new Font("Segoe UI Semibold",11)};f.Controls.Add(fixedBox);f.Controls.Add(new Label{Text="Nombre d’artefacts à conserver",AutoSize=true,Location=new Point(28,58),Font=new Font("Segoe UI Semibold",12)});var number=new NumericUpDown{Minimum=100,Maximum=10000,Increment=50,Value=retentionLimit,ThousandsSeparator=true,Location=new Point(30,95),Size=new Size(180,32),Font=new Font("Segoe UI",12)};var threshold=new Label{AutoSize=false,Location=new Point(28,140),Size=new Size(410,28),ForeColor=Color.FromArgb(116,235,184),Font=new Font("Segoe UI Semibold",11)};f.Controls.Add(new Label{Text="Valeur du seuil fixe (Potential Value)",AutoSize=true,Location=new Point(28,175),Font=new Font("Segoe UI Semibold",12)});var fixedNumber=new NumericUpDown{Minimum=0,Maximum=100,DecimalPlaces=3,Increment=0.1M,Value=(decimal)fixedSellThresholdValue,Location=new Point(30,212),Size=new Size(180,32),Font=new Font("Segoe UI",12)};Action refreshEnabled=()=>{number.Enabled=!fixedBox.Checked;fixedNumber.Enabled=fixedBox.Checked;};Action update=()=>threshold.Text=fixedBox.Checked?"":"Seuil correspondant : "+PreviewRetentionThreshold((int)number.Value).ToString("0.000");number.ValueChanged+=(s,e)=>update();fixedBox.CheckedChanged+=(s,e)=>{refreshEnabled();update();};f.Controls.Add(number);f.Controls.Add(threshold);f.Controls.Add(fixedNumber);Button ok=Btn("APPLIQUER",220,255,105,Teal);f.Controls.Add(ok);Button cancel=Btn("ANNULER",ok.Right+8,255,105,Color.FromArgb(80,90,105));ok.DialogResult=DialogResult.OK;cancel.DialogResult=DialogResult.Cancel;f.Controls.Add(cancel);f.AcceptButton=ok;f.CancelButton=cancel;refreshEnabled();update();if(f.ShowDialog(this)!=DialogResult.OK)return;retentionLimit=(int)number.Value;fixedSellThreshold=fixedBox.Checked;fixedSellThresholdValue=(double)fixedNumber.Value;EngineBridge.RetentionLimit=retentionLimit;EngineBridge.FixedMode=fixedSellThreshold;EngineBridge.FixedValue=fixedSellThresholdValue;SaveRetentionLimit();SaveSellThresholdSettings();ImportCurrent(true);RefreshRetentionButton();status.Text=fixedSellThreshold?"Seuil fixe réglé sur "+fixedSellThresholdValue.ToString("0.000"):"Seuil dynamique réglé sur "+retentionLimit.ToString("N0")+" artefacts • seuil actuel : "+(all.Count==0?0:all.Max(x=>x.RetentionThreshold)).ToString("0.000");}
    void SetupCombo(ComboBox c,int x,int y,int w,string[] items){c.SetBounds(x,y,w,30);c.DropDownStyle=ComboBoxStyle.DropDownList;c.FlatStyle=FlatStyle.Flat;c.BackColor=ComboBg;c.ForeColor=Color.White;c.Items.AddRange(items);c.SelectedIndex=0;c.SelectedIndexChanged+=(s,e)=>RefreshGrid();Controls[0].Controls.Add(c);}
    void AddColumns(){AddIcon("Artefact","Artefact",88);AddAuto("Categorie","Catégorie",92);AddAuto("Restriction","Restriction",128);AddAuto("StatPrincipale","Stat principale",175);AddFixed("Stat1","Stat 1",235);AddFixed("Stat2","Stat 2",235);AddFixed("Stat3","Stat 3",235);AddFixed("Stat4","Stat 4",235);AddTight("Action","Action",105);AddTight("Potential","Potential Value",118);AddFixed("Conversion","Conversion conseillée",345);AddFill("Preset","Meilleur preset",125);}
    void AddAuto(string prop,string header,int minWidth){grid.Columns.Add(new DataGridViewTextBoxColumn{Name=prop,DataPropertyName=prop,HeaderText=header,AutoSizeMode=DataGridViewAutoSizeColumnMode.AllCells,MinimumWidth=minWidth,SortMode=DataGridViewColumnSortMode.NotSortable});}
    void AddTight(string prop,string header,int minWidth){grid.Columns.Add(new DataGridViewTextBoxColumn{Name=prop,DataPropertyName=prop,HeaderText=header,AutoSizeMode=DataGridViewAutoSizeColumnMode.AllCellsExceptHeader,MinimumWidth=minWidth,SortMode=DataGridViewColumnSortMode.NotSortable});}
    void AddFixed(string prop,string header,int width){grid.Columns.Add(new DataGridViewTextBoxColumn{Name=prop,DataPropertyName=prop,HeaderText=header,AutoSizeMode=DataGridViewAutoSizeColumnMode.None,Width=width,MinimumWidth=70,SortMode=DataGridViewColumnSortMode.NotSortable});}
    void AddFill(string prop,string header,int minWidth){grid.Columns.Add(new DataGridViewTextBoxColumn{Name=prop,DataPropertyName=prop,HeaderText=header,AutoSizeMode=DataGridViewAutoSizeColumnMode.Fill,FillWeight=100,MinimumWidth=minWidth,SortMode=DataGridViewColumnSortMode.NotSortable});}
    void AddIcon(string prop,string header,int width){grid.Columns.Add(new DataGridViewTextBoxColumn{Name=prop,DataPropertyName=prop,HeaderText=header,AutoSizeMode=DataGridViewAutoSizeColumnMode.None,Width=width,MinimumWidth=width,SortMode=DataGridViewColumnSortMode.NotSortable});}
    void FormatCell(object s,DataGridViewCellFormattingEventArgs e){var r=grid.Rows[e.RowIndex].DataBoundItem as ArtifactRow;if(r==null)return;if(r.Action=="Sell")e.CellStyle.BackColor=Color.FromArgb(72,18,20);else if(r.Action=="Cible Reappraisal"&&viewMode=="reappraisal")e.CellStyle.BackColor=Color.FromArgb(64,38,90);else e.CellStyle.BackColor=Bg;if(e.ColumnIndex==8)e.CellStyle.ForeColor=r.Action=="Keep"?Color.FromArgb(35,220,125):r.Action=="Cible Reappraisal"?Color.FromArgb(230,125,255):Color.FromArgb(255,105,105);if(e.ColumnIndex==9)e.CellStyle.ForeColor=Color.FromArgb(116,235,184);if(e.ColumnIndex==10)e.CellStyle.ForeColor=Color.FromArgb(235,105,220);if(viewMode=="reappraisal"&&e.ColumnIndex==11)e.CellStyle.ForeColor=r.ReappGain>0?Color.FromArgb(30,235,155):Color.FromArgb(255,135,90);}
    void LoadArtifactIcons(){string dir=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","artifacts");foreach(var name in new[]{"attack","defense","hp","support","water","fire","wind","light","dark"}){string path=Path.Combine(dir,name+".png");if(File.Exists(path)){using(var source=Image.FromFile(path))artifactIcons[name]=new Bitmap(source);}}}
    Image LoadUiImage(string name,int width,int height){try{string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",name);if(File.Exists(path)){using(var source=Image.FromFile(path))return new Bitmap(source,new Size(width,height));}}catch{}return null;}
    // Meme technique que les pierres de reeval dans l'appli Rune Manager (IconBadge +
    // HighQualityScale) : rendu anti-alias/bicubique au lieu du redimensionnement brut de
    // LoadUiImage (flou/pixelise). Utilise pour l'icone du bouton REAPPRAISAL.
    static Bitmap HighQualityScale(Image source,int width,int height){var result=new Bitmap(width,height);using(var g=Graphics.FromImage(result)){g.SmoothingMode=SmoothingMode.AntiAlias;g.InterpolationMode=InterpolationMode.HighQualityBicubic;g.PixelOffsetMode=PixelOffsetMode.HighQuality;g.CompositingQuality=CompositingQuality.HighQuality;g.DrawImage(source,new Rectangle(0,0,width,height));}return result;}
    Image LoadUiImageHQ(string name,int width,int height){try{string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets",name);if(File.Exists(path)){using(var source=Image.FromFile(path))return HighQualityScale(source,width,height);}}catch{}return null;}
    // Le texte de reappButton change apres coup (nombre reel de Core Fragments charge du
    // JSON, remplace le "x0" initial) — sa largeur AutoSize change avec, ce qui laissait un
    // ecart (ou un chevauchement) fige vers priorityButton, positionne une seule fois a la
    // construction. On recale priorityButton a chaque changement de texte de reappButton.
    void RefreshCoreBadge(){if(reappButton==null)return;reappButton.Text="x"+coreFragments.ToString("N0")+"   REAPPRAISAL";if(priorityButton!=null)priorityButton.Left=reappButton.Right+8;}
    string ArtifactIconKey(ArtifactRow r){if(r.Categorie=="Element"){switch(r.Restriction){case "Eau":return "water";case "Feu":return "fire";case "Vent":return "wind";case "Lumiere":return "light";case "Tenebres":return "dark";}}else{switch(r.Restriction){case "Attaque":return "attack";case "Defense":return "defense";case "PV":return "hp";case "Support":return "support";}}return "attack";}
    void PaintArtifactIcon(object sender,DataGridViewCellPaintingEventArgs e){if(e.RowIndex<0||e.ColumnIndex!=0)return;var r=grid.Rows[e.RowIndex].DataBoundItem as ArtifactRow;if(r==null)return;e.PaintBackground(e.CellBounds,true);Image icon;artifactIcons.TryGetValue(ArtifactIconKey(r),out icon);if(icon!=null){Color grade=r.Rarete=="Legendaire"?Color.FromArgb(255,153,0):Color.FromArgb(170,68,221);int frame=Math.Min(32,e.CellBounds.Height-10),x=e.CellBounds.X+(e.CellBounds.Width-frame)/2,y=e.CellBounds.Y+(e.CellBounds.Height-frame)/2;var rect=new Rectangle(x,y,frame,frame);using(var fill=new SolidBrush(Color.FromArgb(25,grade)))e.Graphics.FillRectangle(fill,rect);using(var pen=new Pen(grade,2))e.Graphics.DrawRectangle(pen,rect);int size=Math.Min(24,frame-6),ix=x+(frame-size)/2,iy=y+(frame-size)/2;e.Graphics.InterpolationMode=System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;e.Graphics.DrawImage(icon,new Rectangle(ix,iy,size,size));string level="+"+r.Niveau;using(var font=new Font("Segoe UI Semibold",7,FontStyle.Bold)){SizeF m=e.Graphics.MeasureString(level,font);int bw=(int)Math.Ceiling(m.Width)+4,bh=13;var badge=new Rectangle(rect.Right-bw+3,rect.Bottom-bh+4,bw,bh);using(var b=new SolidBrush(Color.FromArgb(245,5,14,24)))e.Graphics.FillRectangle(b,badge);using(var p=new Pen(Color.FromArgb(100,120,138)))e.Graphics.DrawRectangle(p,badge);TextRenderer.DrawText(e.Graphics,level,font,badge,Color.White,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding);}if(!string.IsNullOrEmpty(r.EquipeSur)){string mp;if(monsterIconByName.TryGetValue(r.EquipeSur,out mp)){var mImg=MonsterImage(mp);if(mImg!=null){int mLeft=e.CellBounds.Left+2,mTop=e.CellBounds.Top+2,mSize=Math.Max(16,Math.Min(rect.Left-mLeft-1,rect.Top-mTop-1));var mBadge=new Rectangle(mLeft,mTop,mSize,mSize);using(var mb=new SolidBrush(Color.FromArgb(245,5,14,24)))e.Graphics.FillRectangle(mb,mBadge);using(var mpen=new Pen(Color.FromArgb(120,200,255)))e.Graphics.DrawRectangle(mpen,mBadge);e.Graphics.DrawImage(mImg,new Rectangle(mBadge.X+1,mBadge.Y+1,mSize-2,mSize-2));}}}grid.Rows[e.RowIndex].Cells[0].ToolTipText=r.Artefact+(string.IsNullOrEmpty(r.EquipeSur)?"":" — équipé sur "+r.EquipeSur);}e.Paint(e.ClipBounds,DataGridViewPaintParts.Border);e.Handled=true;}
    void ChooseJson(){using(var f=new OpenFileDialog{Filter="JSON SWEX (*.json)|*.json",Title="Choisir le fichier JSON SWEX"})if(f.ShowDialog(this)==DialogResult.OK){currentJson=f.FileName;SaveLastJson();ImportCurrent();StartJsonWatcher();}}
    void ImportCurrent(bool automatic=false){
      if(importing)return;if(currentJson.Length==0||!File.Exists(currentJson)){if(!automatic)ChooseJson();return;}
      long topId=automatic?VisibleTopArtifactId():0;int topIndex=automatic?grid.FirstDisplayedScrollingRowIndex:-1;
      try{importing=true;if(!automatic){liveEvents.Clear();liveCoreKnown=false;}UseWaitCursor=true;status.Text=automatic?"Mise à jour automatique en cours…":"Analyse SWLens en cours…";Application.DoEvents();all=EngineBridge.Run(currentJson,"","","",liveEvents,priorityMonsters,reappTargets,soldArtifactIds);var validTargets=new HashSet<long>(all.Where(x=>x.Action=="Cible Reappraisal").Select(x=>x.Rid));if(reappTargets.RemoveWhere(x=>!validTargets.Contains(x))>0)SaveReappSettings();if(!liveCoreKnown)coreFragments=EngineBridge.ReadCoreFragments(currentJson);RefreshCoreBadge();FillFilters();RefreshGrid();if(automatic)RestoreGridPosition(topId,topIndex);status.Text=(automatic?"Mise à jour automatique : ":"Import terminé : ")+Path.GetFileName(currentJson)+" • "+coreFragments.ToString("N0")+" Core Fragments";}catch(Exception ex){if(!automatic)MessageBox.Show(ex.Message,"Artifact Manager",MessageBoxButtons.OK,MessageBoxIcon.Error);else status.Text="Mise à jour automatique reportée : "+ex.Message;}finally{UseWaitCursor=false;importing=false;}
    }
    long VisibleTopArtifactId(){int i=grid.FirstDisplayedScrollingRowIndex;if(i<0||i>=grid.Rows.Count)return 0;var row=grid.Rows[i].DataBoundItem as ArtifactRow;return row==null?0:row.Rid;}
    void RestoreGridPosition(long id,int fallback){if(grid.Rows.Count==0)return;int target=-1;if(id>0)for(int i=0;i<grid.Rows.Count;i++){var row=grid.Rows[i].DataBoundItem as ArtifactRow;if(row!=null&&row.Rid==id){target=i;break;}}if(target<0)target=Math.Min(Math.Max(0,fallback),grid.Rows.Count-1);try{grid.FirstDisplayedScrollingRowIndex=target;}catch{}}
    void MonsterView(string cat,string mode){if(currentJson.Length==0||!File.Exists(currentJson)){ChooseJson();return;}string m=Convert.ToString(monster.Text).Trim();if(m.Length==0){MessageBox.Show("Choisis d’abord un monstre.","Artifact Manager");return;}try{UseWaitCursor=true;all=EngineBridge.Run(currentJson,m,cat,mode,liveEvents,priorityMonsters,reappTargets,soldArtifactIds);obtainedSort=false;viewMode="monstre";FillFilters();RefreshGrid();status.Text="Classement "+m+" — "+cat+" — "+mode;}catch(Exception ex){MessageBox.Show(ex.Message,"Artifact Manager",MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{UseWaitCursor=false;}}
    void ShowFullList(bool byObtained){if(currentJson.Length==0||!File.Exists(currentJson)){obtainedSort=byObtained;viewMode=byObtained?"obtained":"potential";RefreshGrid();return;}try{UseWaitCursor=true;all=EngineBridge.Run(currentJson,"","","",liveEvents,priorityMonsters,reappTargets,soldArtifactIds);obtainedSort=byObtained;viewMode=byObtained?"obtained":"potential";FillFilters();RefreshGrid();status.Text=byObtained?"Tri par date d’obtention — tous les artefacts":"Tri par Potential Value — tous les artefacts";}catch(Exception ex){MessageBox.Show(ex.Message,"Artifact Manager",MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{UseWaitCursor=false;}}
    void ShowGlobalReappraisal(){if(currentJson.Length==0||!File.Exists(currentJson)){ChooseJson();return;}if(priorityMonsters.Count==0){ShowPriorityMonsters();if(priorityMonsters.Count==0)return;}try{UseWaitCursor=true;status.Text="Analyse des artefacts compatibles avec les monstres Reappraisal prioritaires…";Application.DoEvents();all=EngineBridge.Run(currentJson,"","","",liveEvents,priorityMonsters,reappTargets,soldArtifactIds);obtainedSort=false;viewMode="reappraisal";FillFilters();RefreshGrid();double top10=TopTenThreshold();status.Text="Reappraisal — "+priorityMonsters.Count+" monstre(s) prioritaire(s) • artefacts du top 10 % exclus • coût : 10 fragments";}catch(Exception ex){MessageBox.Show(ex.Message,"Artifact Manager",MessageBoxButtons.OK,MessageBoxIcon.Error);}finally{UseWaitCursor=false;}}
    double TopTenThreshold(){if(all.Count==0)return 0;var scores=all.Select(x=>x.Potential).OrderByDescending(x=>x).ToList();int count=Math.Max(1,(int)Math.Ceiling(scores.Count*.10));return scores[Math.Min(scores.Count-1,count-1)];}
    string SettingsDir{get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"ArtifactManagerModern");}}
    string PriorityPath{get{return Path.Combine(SettingsDir,"reapp_priority_monsters.txt");}}string TargetPath{get{return Path.Combine(SettingsDir,"reapp_targets.txt");}}string SoldPath{get{return Path.Combine(SettingsDir,"sold_artifacts.txt");}}string PriorityMigrationPath{get{return Path.Combine(SettingsDir,"priority_targets_v2.done");}}
    void LoadReappSettings(){try{Directory.CreateDirectory(SettingsDir);if(File.Exists(PriorityPath))foreach(var x in File.ReadAllLines(PriorityPath,Encoding.UTF8))if(x.Trim().Length>0)priorityMonsters.Add(x.Trim());if(File.Exists(TargetPath))foreach(var x in File.ReadAllLines(TargetPath,Encoding.UTF8)){long id;if(long.TryParse(x,out id)&&id>0)reappTargets.Add(id);}if(File.Exists(SoldPath))foreach(var x in File.ReadAllLines(SoldPath,Encoding.UTF8)){long id;if(long.TryParse(x,out id)&&id>0)soldArtifactIds.Add(id);}}catch{}}
    void SaveReappSettings(){try{Directory.CreateDirectory(SettingsDir);File.WriteAllLines(PriorityPath,priorityMonsters.OrderBy(x=>x).ToArray(),Encoding.UTF8);File.WriteAllLines(TargetPath,reappTargets.OrderBy(x=>x).Select(x=>x.ToString()).ToArray(),Encoding.UTF8);File.WriteAllLines(SoldPath,soldArtifactIds.OrderBy(x=>x).Select(x=>x.ToString()).ToArray(),Encoding.UTF8);if(priorityButton!=null)priorityButton.Text="MONSTRES REAPP : "+priorityMonsters.Count;}catch{}}
    void ShowPriorityMonsters(){LoadMonsters();var selected=new HashSet<string>(priorityMonsters,StringComparer.OrdinalIgnoreCase);var f=new Form{Text="Monstres prioritaires — Reappraisal",Size=new Size(760,680),StartPosition=FormStartPosition.CenterParent,BackColor=Bg,ForeColor=Color.White,Font=Font};var title=new Label{Text="Choisis les monstres dont les artefacts doivent être prioritaires",Dock=DockStyle.Top,Height=45,TextAlign=ContentAlignment.MiddleCenter,Font=new Font("Segoe UI Semibold",12)};var find=new TextBox{Dock=DockStyle.Top,Height=32,BackColor=Panel,ForeColor=Color.White,BorderStyle=BorderStyle.FixedSingle};var flow=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,Padding=new Padding(8),BackColor=Bg};var bottom=new Panel{Dock=DockStyle.Bottom,Height=55,BackColor=Panel};var count=new Label{Location=new Point(12,12),Size=new Size(360,32),ForeColor=Color.FromArgb(116,235,184),TextAlign=ContentAlignment.MiddleLeft};var save=Btn("VALIDER",600,10,130,Color.FromArgb(99,55,160));bottom.Controls.Add(count);bottom.Controls.Add(save);Action rebuild=null;rebuild=()=>{flow.SuspendLayout();flow.Controls.Clear();string q=find.Text.Trim();IEnumerable<MonsterOption> shown=q.Length==0?monsterOptions.OrderByDescending(x=>selected.Contains(x.Name)).ThenBy(x=>x.Name).Take(160):monsterOptions.Where(x=>x.Name.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0||x.Family.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0).OrderByDescending(x=>selected.Contains(x.Name)).ThenBy(x=>x.Name).Take(200);foreach(var o in shown){var b=new Button{Text=o.Name+"\r\n"+o.Family,Tag=o,Size=new Size(224,64),TextAlign=ContentAlignment.MiddleLeft,ImageAlign=ContentAlignment.MiddleLeft,TextImageRelation=TextImageRelation.ImageBeforeText,Padding=new Padding(5),ForeColor=Color.White,BackColor=selected.Contains(o.Name)?Color.FromArgb(99,55,160):Panel,FlatStyle=FlatStyle.Flat};var img=MonsterImage(o.ImagePath);if(img!=null)b.Image=new Bitmap(img,new Size(46,46));b.Click+=(s,e)=>{if(selected.Contains(o.Name))selected.Remove(o.Name);else selected.Add(o.Name);rebuild();};flow.Controls.Add(b);}count.Text=selected.Count+" monstre(s) prioritaire(s)";flow.ResumeLayout();};find.TextChanged+=(s,e)=>rebuild();save.Click+=(s,e)=>{priorityMonsters.Clear();foreach(var x in selected)priorityMonsters.Add(x);SaveReappSettings();f.DialogResult=DialogResult.OK;f.Close();};f.Controls.Add(flow);f.Controls.Add(find);f.Controls.Add(title);f.Controls.Add(bottom);rebuild();if(f.ShowDialog(this)==DialogResult.OK&&currentJson.Length>0){RebuildPriorityTargets();ImportCurrent(true);status.Text=reappTargets.Count+" artefact(s) sous le seuil classé(s) Cible Reappraisal pour les monstres prioritaires";}}
    static string TargetMonsterFromReason(string reason){if(string.IsNullOrEmpty(reason))return "";int bar=reason.IndexOf('|');if(bar<0)return "";string tail=reason.Substring(bar+1).Trim();int dash=tail.IndexOf('—');return (dash<0?tail:tail.Substring(0,dash)).Trim();}
    void RebuildPriorityTargets(){if(currentJson.Length==0||!File.Exists(currentJson)||priorityMonsters.Count==0){reappTargets.Clear();SaveReappSettings();return;}try{UseWaitCursor=true;var baseline=EngineBridge.Run(currentJson,"","","",liveEvents,priorityMonsters,Enumerable.Empty<long>(),soldArtifactIds);double threshold=baseline.Count==0?0:baseline.Max(x=>x.RetentionThreshold);var scores=baseline.Select(x=>x.Potential).OrderByDescending(x=>x).ToList();double top10=scores.Count==0?0:scores[Math.Min(scores.Count-1,Math.Max(1,(int)Math.Ceiling(scores.Count*.10))-1)];reappTargets.Clear();var eligible=baseline.Where(x=>x.Niveau>=15&&x.Rarete=="Legendaire").ToList();foreach(var x in eligible.Where(x=>x.ReappPriority>=top10&&x.Potential<threshold))reappTargets.Add(x.Rid);
      // Monstres prioritaires sans aucun artefact atteignant le top 10 % : seuil relâché pour eux, sinon ils ne reçoivent jamais de cible.
      var coveredMonsters=new HashSet<string>(eligible.Where(x=>x.ReappPriority>=top10).Select(x=>TargetMonsterFromReason(x.ReappReason)).Where(m=>m.Length>0),StringComparer.OrdinalIgnoreCase);
      var starved=new HashSet<string>(priorityMonsters.Where(m=>!coveredMonsters.Contains(m)),StringComparer.OrdinalIgnoreCase);
      if(starved.Count>0)foreach(var x in eligible.Where(x=>x.Potential<threshold&&starved.Contains(TargetMonsterFromReason(x.ReappReason))))reappTargets.Add(x.Rid);
      SaveReappSettings();}finally{UseWaitCursor=false;}}
    void FillFilters(){SetItems(category,"Toutes catégories",all.Select(x=>x.Categorie));SetItems(restriction,"Toutes restrictions",all.Select(x=>x.Restriction));SetItems(action,"Toutes actions",all.Select(x=>x.Action));SetItems(preset,"Tous les presets",all.Select(x=>x.Preset));LoadMonsters();}
    void SetItems(ComboBox c,string first,IEnumerable<string> values){string old=Convert.ToString(c.SelectedItem);c.BeginUpdate();c.Items.Clear();c.Items.Add(first);foreach(var x in values.Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct().OrderBy(x=>x))c.Items.Add(x);c.SelectedItem=c.Items.Contains(old)?old:first;c.EndUpdate();}
    void LoadMonsters(){if(monsterOptions.Count>0)return;try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue};var root=(Dictionary<string,object>)js.DeserializeObject(File.ReadAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Artifact_Manager_Data.json")));string dir=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"assets","monsters"),catalogPath=Path.Combine(dir,"catalog.json");var catalogById=new Dictionary<int,Dictionary<string,object>>();if(File.Exists(catalogPath))foreach(var raw in js.DeserializeObject(File.ReadAllText(catalogPath,Encoding.UTF8)) as object[]??new object[0]){var d=raw as Dictionary<string,object>;if(d!=null&&d.ContainsKey("id"))catalogById[Convert.ToInt32(d["id"])]=d;}var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);object profilesRaw;if(root.TryGetValue("profiles",out profilesRaw))foreach(var raw in profilesRaw as object[]??new object[0]){var p=raw as Dictionary<string,object>;if(p==null||!p.ContainsKey("monster"))continue;string name=Convert.ToString(p["monster"]);int id=p.ContainsKey("monster_id")?Convert.ToInt32(p["monster_id"]):0;string unique=id+"|"+name;if(name.Length==0||!seen.Add(unique))continue;Dictionary<string,object> c;catalogById.TryGetValue(id,out c);string imgPath=id>0?Path.Combine(dir,id+".png"):"";monsterOptions.Add(new MonsterOption{Id=id,Name=name,Family=c!=null&&c.ContainsKey("family")?Convert.ToString(c["family"]):"",Element=c!=null&&c.ContainsKey("element")?Convert.ToString(c["element"]):p.ContainsKey("element")?Convert.ToString(p["element"]):"",ImagePath=imgPath});if(imgPath.Length>0&&!monsterIconByName.ContainsKey(name))monsterIconByName[name]=imgPath;}monsterOptions.Sort((a,b)=>{int n=string.Compare(a.Name,b.Name,StringComparison.OrdinalIgnoreCase);return n!=0?n:string.Compare(a.Element,b.Element,StringComparison.OrdinalIgnoreCase);});monster.Items.AddRange(monsterOptions.Cast<object>().ToArray());}catch(Exception ex){status.Text="Catalogue SWLens indisponible : "+ex.Message;}}
    void FilterMonsterChoices(){if(filteringMonsters||monsterOptions.Count==0)return;string typed=monster.Text;int caret=monster.SelectionStart;var matches=monsterOptions.Where(x=>x.Name.IndexOf(typed,StringComparison.OrdinalIgnoreCase)>=0||x.Family.IndexOf(typed,StringComparison.OrdinalIgnoreCase)>=0).Take(80).Cast<object>().ToArray();try{filteringMonsters=true;monster.BeginUpdate();monster.Items.Clear();monster.Items.AddRange(matches);monster.Text=typed;monster.SelectionStart=Math.Min(caret,typed.Length);monster.SelectionLength=0;monster.DroppedDown=typed.Length>0&&matches.Length>0;}finally{monster.EndUpdate();filteringMonsters=false;}}
    Image MonsterImage(string path){if(string.IsNullOrWhiteSpace(path)||!File.Exists(path))return null;Image image;if(monsterImages.TryGetValue(path,out image))return image;try{using(var source=Image.FromFile(path))image=new Bitmap(source);monsterImages[path]=image;return image;}catch{return null;}}
    void DrawMonsterItem(object sender,DrawItemEventArgs e){e.DrawBackground();if(e.Index<0){e.DrawFocusRectangle();return;}var option=monster.Items[e.Index] as MonsterOption;if(option==null){TextRenderer.DrawText(e.Graphics,Convert.ToString(monster.Items[e.Index]),Font,e.Bounds,Color.White,TextFormatFlags.Left|TextFormatFlags.VerticalCenter);return;}bool selected=(e.State&DrawItemState.Selected)!=0;Color back=selected?Color.FromArgb(45,54,57):Bg;using(var b=new SolidBrush(back))e.Graphics.FillRectangle(b,e.Bounds);var icon=MonsterImage(option.ImagePath);int size=Math.Min(40,e.Bounds.Height-6),x=e.Bounds.X+5,y=e.Bounds.Y+(e.Bounds.Height-size)/2;if(icon!=null)e.Graphics.DrawImage(icon,new Rectangle(x,y,size,size));using(var nameFont=new Font("Segoe UI Semibold",10)){TextRenderer.DrawText(e.Graphics,option.Name,nameFont,new Rectangle(x+size+8,e.Bounds.Y+4,e.Bounds.Width-size-72,21),Color.White,TextFormatFlags.Left|TextFormatFlags.EndEllipsis);}using(var familyFont=new Font("Segoe UI",8)){TextRenderer.DrawText(e.Graphics,option.Family,familyFont,new Rectangle(x+size+8,e.Bounds.Y+24,e.Bounds.Width-size-72,18),Color.FromArgb(175,175,175),TextFormatFlags.Left|TextFormatFlags.EndEllipsis);}Color ec=option.Element=="fire"?Color.FromArgb(235,75,65):option.Element=="water"?Color.FromArgb(45,145,235):option.Element=="wind"?Color.FromArgb(225,185,45):option.Element=="light"?Color.FromArgb(225,215,170):Color.FromArgb(150,90,190);using(var b=new SolidBrush(ec))e.Graphics.FillEllipse(b,e.Bounds.Right-24,e.Bounds.Y+(e.Bounds.Height-14)/2,14,14);e.DrawFocusRectangle();}
    void RefreshGrid(){IEnumerable<ArtifactRow> q=all;string text=search.Text.Trim();if(text.Length>0)q=q.Where(x=>(x.Artefact+" "+x.StatPrincipale+" "+x.Stat1+" "+x.Stat2+" "+x.Stat3+" "+x.Stat4+" "+x.Preset+" "+x.EquipeSur).IndexOf(text,StringComparison.OrdinalIgnoreCase)>=0);if(category.SelectedIndex>0)q=q.Where(x=>x.Categorie==Convert.ToString(category.SelectedItem));if(restriction.SelectedIndex>0)q=q.Where(x=>x.Restriction==Convert.ToString(restriction.SelectedItem));if(action.SelectedIndex>0)q=q.Where(x=>x.Action==Convert.ToString(action.SelectedItem));if(preset.SelectedIndex>0)q=q.Where(x=>x.Preset==Convert.ToString(preset.SelectedItem));bool reapp=viewMode=="reappraisal";grid.Columns[9].DataPropertyName="Potential";grid.Columns[9].HeaderText=reapp?"Score actuel":"Potential Value";grid.Columns[10].DataPropertyName=reapp?"ReappPriority":"Conversion";grid.Columns[10].HeaderText=reapp?"Maximum avec 4 rolls":"Conversion conseillée";grid.Columns[11].DataPropertyName=reapp?"ReappGain":"Preset";grid.Columns[11].HeaderText=reapp?"Gain potentiel":"Meilleur preset";double top10=TopTenThreshold();if(reapp)q=q.Where(x=>x.Niveau>=15&&x.Rarete=="Legendaire"&&(x.Action=="Cible Reappraisal"||(x.Action=="Keep"&&x.ReappPriority>=top10&&x.Potential<top10))).OrderByDescending(x=>x.Action=="Cible Reappraisal").ThenByDescending(x=>x.ReappGain).ThenByDescending(x=>x.ReappPriority).ThenBy(x=>x.Potential).ThenByDescending(x=>x.Rid);else q=obtainedSort?q.OrderByDescending(x=>x.ObtainedDate).ThenByDescending(x=>x.Rid):q.OrderByDescending(x=>x.Potential);var list=q.ToList();grid.DataSource=new BindingList<ArtifactRow>(list);var keptAll=all.Where(x=>x.Action=="Keep").ToList();int targetCount=all.Count(x=>x.Action=="Cible Reappraisal");int sellCount=all.Count(x=>x.Action=="Sell");double threshold=all.Count==0?0:all.Max(x=>x.RetentionThreshold);summary.Text="TOTAL  "+all.Count.ToString("N0")+"     KEEP  "+keptAll.Count.ToString("N0")+"     SELL  "+sellCount.ToString("N0")+"     CIBLE REAPPRAISAL  "+targetCount.ToString("N0")+"     AFFICHÉES  "+list.Count.ToString("N0")+"     seuil "+threshold.ToString("0.000")+" pour "+keptAll.Count.ToString("N0")+"/"+retentionLimit.ToString("N0")+(reapp?" • top 10 % ≥ "+top10.ToString("0.000")+" exclus • "+priorityMonsters.Count+" monstre(s) prioritaire(s) • "+coreFragments.ToString("N0")+" fragments":"");}
    void StartRealtime(){StartJsonWatcher();StartLiveLog();}
    void StartJsonWatcher(){if(string.IsNullOrWhiteSpace(currentJson)||!File.Exists(currentJson))return;try{if(jsonWatcher!=null)jsonWatcher.Dispose();jsonWatcher=new FileSystemWatcher(Path.GetDirectoryName(currentJson),Path.GetFileName(currentJson));jsonWatcher.NotifyFilter=NotifyFilters.LastWrite|NotifyFilters.Size|NotifyFilters.FileName;jsonWatcher.Changed+=(s,e)=>QueueJson(e.FullPath);jsonWatcher.Created+=(s,e)=>QueueJson(e.FullPath);jsonWatcher.Renamed+=(s,e)=>QueueJson(e.FullPath);jsonWatcher.EnableRaisingEvents=true;status.Text=(status.Text.Length>0?status.Text+" • ":"")+"Surveillance JSON active";}catch(Exception ex){status.Text="Surveillance JSON indisponible : "+ex.Message;}}
    void QueueJson(string path){if(IsDisposed)return;BeginInvoke((Action)(()=>{pendingJson=path;jsonDebounce.Stop();jsonDebounce.Start();}));}
    void StartLiveLog(){liveLogPath=@"C:\Users\Great-Lucky\Desktop\Summoners War Exporter Files\full_log.txt";try{int recovered=0;if(soldArtifactIds.Count==0&&File.Exists(liveLogPath)){foreach(string line in File.ReadLines(liveLogPath,Encoding.UTF8)){if(line.IndexOf("\"command\":\"SellArtifacts\"",StringComparison.OrdinalIgnoreCase)<0||line.IndexOf("\"ret_code\":0",StringComparison.OrdinalIgnoreCase)<0)continue;foreach(long id in EngineBridge.SoldArtifactIds(line))if(soldArtifactIds.Add(id))recovered++;}if(recovered>0){SaveReappSettings();ImportCurrent(true);}}liveLogOffset=File.Exists(liveLogPath)?new FileInfo(liveLogPath).Length:0;liveLogPending="";liveAwaitingResponse=false;liveLogTimer.Start();status.Text=(status.Text.Length>0?status.Text+" • ":"")+"Mise à jour SWEX active"+(recovered>0?" • "+recovered+" vente(s) historique(s) restaurée(s)":"");}catch(Exception ex){status.Text="Surveillance SWEX indisponible : "+ex.Message;}}
    void ReadLiveLog(){if(string.IsNullOrWhiteSpace(liveLogPath)||!File.Exists(liveLogPath))return;try{using(var fs=new FileStream(liveLogPath,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete)){if(fs.Length<liveLogOffset){liveLogOffset=0;liveLogPending="";liveAwaitingResponse=false;}if(fs.Length==liveLogOffset)return;fs.Seek(liveLogOffset,SeekOrigin.Begin);using(var sr=new StreamReader(fs,Encoding.UTF8,true,4096,true)){liveLogPending+=sr.ReadToEnd();liveLogOffset=fs.Position;}}ProcessLiveLog();}catch(IOException){}catch(UnauthorizedAccessException){}catch(Exception ex){status.Text="Lecture SWEX interrompue : "+ex.Message;}}
    void ProcessLiveLog(){string normalized=liveLogPending.Replace("\r\n","\n");int last=normalized.LastIndexOf('\n');if(last<0)return;string complete=normalized.Substring(0,last+1);liveLogPending=normalized.Substring(last+1);bool artifactChanged=false,rosterChanged=false,coreChanged=false,settingsChanged=false;foreach(string raw in complete.Split(new[]{'\n'})){string line=raw.Trim();if(line=="Response:"){liveAwaitingResponse=true;continue;}if(line=="Request:"){liveAwaitingResponse=false;continue;}if(!liveAwaitingResponse||line.Length==0)continue;liveAwaitingResponse=false;int found;if(TryReadLiveCoreFragments(line,out found)&&found!=coreFragments){coreFragments=found;liveCoreKnown=true;coreChanged=true;}var sold=EngineBridge.SoldArtifactIds(line);if(sold.Count>0){foreach(long id in sold){if(soldArtifactIds.Add(id))settingsChanged=true;if(reappTargets.Remove(id))settingsChanged=true;}liveEvents.Add(line);if(liveEvents.Count>300)liveEvents.RemoveAt(0);artifactChanged=true;continue;}var ids=EngineBridge.ArtifactIds(line);var comparison=EngineBridge.CompareReappraisal(currentJson,liveEvents,line);if(comparison!=null){foreach(long id in ids)if(reappTargets.Remove(id))settingsChanged=true;ShowReappraisalDecision(comparison);artifactChanged=true;continue;}if(IsMutableArtifactEvent(line)||IsMonsterRosterEvent(line)){liveEvents.Add(line);if(liveEvents.Count>300)liveEvents.RemoveAt(0);if(IsMonsterRosterEvent(line))rosterChanged=true;else{artifactChanged=true;if(!IsArtifactReappraisalEvent(line))foreach(long id in ids)if(reappTargets.Add(id))settingsChanged=true;}}}if(settingsChanged)SaveReappSettings();if(artifactChanged||rosterChanged){ImportCurrent(true);if(rosterChanged)status.Text="Nouveau monstre détecté : scores et seuil des 1 500 artefacts recalculés en temps réel";else status.Text=soldArtifactIds.Count+" artefact(s) vendu(s) conservé(s) hors de la liste • ordre Obtained recalculé";}else if(coreChanged){RefreshCoreBadge();RefreshGrid();status.Text="Core Fragments synchronisés en temps réel : "+coreFragments.ToString("N0");}}
    void ShowReappraisalDecision(ArtifactReappraisalComparison c){var f=new Form{Text="Choix de Reappraisal",Size=new Size(670,390),StartPosition=FormStartPosition.Manual,TopMost=true,BackColor=Bg,ForeColor=Color.White,FormBorderStyle=FormBorderStyle.FixedToolWindow,ShowInTaskbar=false};var area=Screen.PrimaryScreen.WorkingArea;f.Location=new Point(area.Right-f.Width-20,area.Top+20);string verdict=c.TakeAfter?"PRENDRE LE NOUVEL ARTEFACT":"GARDER L’ARTEFACT ACTUEL";Color verdictColor=c.TakeAfter?Color.FromArgb(30,235,155):Color.FromArgb(255,190,60);var title=new Label{Text=verdict,ForeColor=verdictColor,Font=new Font("Segoe UI",17,FontStyle.Bold),AutoSize=false,TextAlign=ContentAlignment.MiddleCenter,Dock=DockStyle.Top,Height=58};var beforeLabel=ComparisonPanel("ACTUEL",c.Before,new Point(18,70));var afterLabel=ComparisonPanel("NOUVEAU",c.After,new Point(340,70));var delta=new Label{Text="Écart de Potential : "+(c.After.Potential-c.Before.Potential).ToString("+0.000;-0.000;0.000"),ForeColor=verdictColor,Font=new Font("Segoe UI Semibold",11),AutoSize=false,TextAlign=ContentAlignment.MiddleCenter,Location=new Point(18,310),Size=new Size(626,28)};var close=new Button{Text="FERMER",Location=new Point(524,342),Size=new Size(120,30),BackColor=Color.FromArgb(180,45,65),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};close.Click+=(s,e)=>f.Close();f.Controls.Add(title);f.Controls.Add(beforeLabel);f.Controls.Add(afterLabel);f.Controls.Add(delta);f.Controls.Add(close);f.Show(this);}
    Control ComparisonPanel(string heading,ArtifactRow r,Point location){return new Label{Text=heading+"\r\nPotential  "+r.Potential.ToString("0.000")+"\r\nPreset : "+r.Preset+"\r\n\r\n"+r.StatPrincipale+"\r\n"+r.Stat1+"\r\n"+r.Stat2+"\r\n"+r.Stat3+"\r\n"+r.Stat4,Font=new Font("Segoe UI",10),AutoSize=false,Location=location,Size=new Size(304,232),Padding=new Padding(10),BackColor=Panel};}
    bool IsMutableArtifactEvent(string json){if(json.IndexOf("\"artifact",StringComparison.OrdinalIgnoreCase)<0)return false;try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var root=js.DeserializeObject(json) as Dictionary<string,object>;object c;if(root==null||!root.TryGetValue("command",out c))return false;string command=Convert.ToString(c);return !(command.StartsWith("Get",StringComparison.OrdinalIgnoreCase)||command.StartsWith("Hub",StringComparison.OrdinalIgnoreCase)||command.IndexOf("List",StringComparison.OrdinalIgnoreCase)>=0||command.IndexOf("Info",StringComparison.OrdinalIgnoreCase)>=0);}catch{return false;}}
    bool IsArtifactReappraisalEvent(string json){try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var root=js.DeserializeObject(json) as Dictionary<string,object>;object c;return root!=null&&root.TryGetValue("command",out c)&&EngineBridge.IsReappraisalCommand(Convert.ToString(c));}catch{return false;}}
    bool IsMonsterRosterEvent(string json){if(json.IndexOf("\"unit_master_id\"",StringComparison.OrdinalIgnoreCase)<0)return false;try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};var root=js.DeserializeObject(json) as Dictionary<string,object>;object c;if(root==null||!root.TryGetValue("command",out c))return false;string command=Convert.ToString(c);return command.Equals("SummonUnit",StringComparison.OrdinalIgnoreCase)||command.IndexOf("Storage",StringComparison.OrdinalIgnoreCase)>=0;}catch{return false;}}
    bool TryReadLiveCoreFragments(string json,out int amount){amount=-1;try{var js=new JavaScriptSerializer{MaxJsonLength=int.MaxValue,RecursionLimit=256};return FindCoreFragments(js.DeserializeObject(json),ref amount);}catch{return false;}}
    bool FindCoreFragments(object value,ref int amount){var d=value as Dictionary<string,object>;if(d!=null){object t,id,q;if(d.TryGetValue("item_master_type",out t)&&d.TryGetValue("item_master_id",out id)&&Convert.ToInt32(t)==75&&Convert.ToInt32(id)==2&&(d.TryGetValue("item_quantity_curr",out q)||d.TryGetValue("item_quantity",out q))&&(d.ContainsKey("rid")||d.ContainsKey("wizard_id")||d.ContainsKey("item_quantity_curr"))){amount=Math.Max(0,Convert.ToInt32(q));return true;}bool found=false;foreach(var kv in d)if(FindCoreFragments(kv.Value,ref amount))found=true;return found;}bool any=false;foreach(var x in value as object[]??new object[0])if(FindCoreFragments(x,ref amount))any=true;return any;}
    string LastPath{get{return Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"artifact_last_json.txt");}}void SaveLastJson(){try{File.WriteAllText(LastPath,currentJson);}catch{}}void LoadLastJson(){try{if(File.Exists(LastPath)){currentJson=File.ReadAllText(LastPath).Trim();if(File.Exists(currentJson)){if(priorityMonsters.Count>0&&!File.Exists(PriorityMigrationPath)){RebuildPriorityTargets();File.WriteAllText(PriorityMigrationPath,DateTime.Now.ToString("O"));}ImportCurrent();}}}catch{}}
  }
}
