using System;
using System.Collections.Generic;

namespace RuneManagerModern {
  static class Loc {
    public static string Lang="fr";
    public static bool En { get { return Lang=="en"; } }
    static readonly Dictionary<string,string> Fr=new Dictionary<string,string>(StringComparer.Ordinal);
    static readonly Dictionary<string,string> EnMap=new Dictionary<string,string>(StringComparer.Ordinal);
    static Loc(){
      Add("app_title","Rune Manager — Application Preview","Rune Manager — Application Preview");
      Add("import_json","IMPORTER JSON","IMPORT JSON");
      Add("sort_potential","Tri Potential Value","Potential Value sort");
      Add("sort_obtained","Tri Obtained","Obtained sort");
      Add("sort_upgrade","Tri Amélioration Disponible","Available Upgrade sort");
      Add("sort_reeval","TRI REEVAL","REAPP SORT");
      Add("sort_refinement","TRI REFINEMENT","REFINEMENT SORT");
      Add("preset","Preset","Preset");
      Add("coefficient","Coefficient","Coefficient");
      Add("autokeep","Auto-Keep","Auto-Keep");
      Add("rules","Règles","Rules");
      Add("skillup","SKILL-UP 4★","SKILL-UP 4★");
      Add("rta","RTA  PICK / BAN","RTA  PICK / BAN");
      Add("spd_rank","CLASSEMENT SPD","SPD RANKING");
      Add("lang_switch","EN","FR");
      Add("filter_all_sets","Tous les sets","All sets");
      Add("filter_all_slots","Tous les slots","All slots");
      Add("filter_all_actions","Toutes actions","All actions");
      Add("filter_all_presets","Tous presets","All presets");
      Add("filter_all_runes","Toutes les runes","All runes");
      Add("filter_normal","Normales uniquement","Normal only");
      Add("filter_ancient","Antiques uniquement","Ancient only");
      Add("col_rune","Rune / Slot","Rune / Slot");
      Add("col_main","Stat principale","Main stat");
      Add("col_innate","Innate","Innate");
      Add("col_innate_val","Valeur innate","Innate value");
      Add("col_stat1","Stat 1","Stat 1");
      Add("col_stat2","Stat 2","Stat 2");
      Add("col_stat3","Stat 3","Stat 3");
      Add("col_stat4","Stat 4","Stat 4");
      Add("col_action","Action","Action");
      Add("col_potential","Potential Value","Potential Value");
      Add("col_gem","Gemme conseillée","Suggested gem");
      Add("col_preset","Meilleur preset","Best preset");
      Add("col_refine_pot","Potential moyen attendu","Expected average potential");
      Add("col_refine_gain","Gain moyen attendu","Expected average gain");
      Add("col_refine_preset","Meilleur preset attendu","Expected best preset");
      Add("status_potential","Tri Potential Value — seuil +12 : {0}","Potential Value sort — +12 threshold: {0}");
      Add("status_upgrade","Runes +12 minimum améliorables avec le stock disponible — seuil : {0}","+12 runes upgradable with current stock — threshold: {0}");
      Add("status_refinement","Runes raffinables — slot/set le plus faible en SPD d'abord, pire Potential Value en premier","Refinable runes — weakest SPD set/slot first, lowest Potential Value first");
      Add("status_obtained","{0} runes — Tri Obtained","{0} runes — Obtained sort");
      Add("status_reeval","{0} runes Reeval — slot/set le plus faible en SPD d'abord, pire Potential Value en premier (max 10)","{0} Reeval runes — weakest SPD set/slot first, lowest Potential Value first (max 10)");
      Add("status_json_watch","Surveillance JSON active","JSON watch active");
      Add("status_json_watch_fail","Surveillance JSON indisponible : {0}","JSON watch unavailable: {0}");
      Add("status_swex_on","Mise à jour SWEX active • {0}","SWEX live update on • {0}");
      Add("status_swex_missing","Journal SWEX (full_log.txt) introuvable dans {0}. Active FullLogger dans SWEX.","SWEX log (full_log.txt) not found in {0}. Enable FullLogger in SWEX.");
      Add("status_swex_fail","Surveillance SWEX indisponible : {0}","SWEX watch unavailable: {0}");
      Add("status_swex_read","Lecture SWEX interrompue : {0}","SWEX read interrupted: {0}");
      Add("status_json_detected","Nouveau JSON détecté — attente de la fin de l'export…","New JSON detected — waiting for export to finish…");
      Add("status_json_imported","{0} runes — JSON importé automatiquement : {1}","{0} runes — JSON auto-imported: {1}");
      Add("status_importing","Import et calcul en cours…","Import and calculation in progress…");
      Add("status_imported","{0} runes analysées en {1} s — seuil dynamique des {2} meilleures : {3} — {4}","{0} runes analyzed in {1} s — dynamic threshold of top {2}: {3} — {4}");
      Add("status_import_fail","Import impossible : {0}","Import failed: {0}");
      Add("status_live_done"," — recalcul automatique terminé"," — automatic recalculation done");
      Add("status_skill_updated","Inventaire Skill-Up mis à jour","Skill-Up inventory updated");
      Add("status_wb_equip","Équipement World Boss mis à jour","World Boss equipment updated");
      Add("status_stock_live","Stock gemmes/meules synchronisé en temps réel","Gem/grindstone stock synced live");
      Add("status_reapp_live","Pierres de réévaluation synchronisées en temps réel","Reappraisal stones synced live");
      Add("status_refine_live","Pierres de raffinage synchronisées en temps réel","Refinement stones synced live");
      Add("counters","TOTAL  {0}     KEEP  {1}     PWR UP  {2}     SELL  {3}     AFFICHÉES  {4}","TOTAL  {0}     KEEP  {1}     PWR UP  {2}     SELL  {3}     SHOWN  {4}");
      Add("counters_reeval","TOTAL  {0}     REEVAL  {1}     NORMALES  {2}     ANTIQUES  {3}     AFFICHÉES  {4}","TOTAL  {0}     REEVAL  {1}     NORMAL  {2}     ANCIENT  {3}     SHOWN  {4}");
      Add("seuil_fixe","SEUIL FIXE  •  {0}","FIXED THRESHOLD  •  {0}");
      Add("seuil_dyn","SEUIL DYNAMIQUE  {0}  •  {1}","DYNAMIC THRESHOLD  {0}  •  {1}");
      Add("eco_mana","  •  ECO MANA","  •  MANA SAVE");
      Add("open_json","Choisir le fichier JSON","Choose JSON file");
      Add("filter_json","Export Summoners War (*.json)|*.json","Summoners War export (*.json)|*.json");
      Add("ok","OK","OK");
      Add("cancel","Annuler","Cancel");
      Add("close","FERMER","CLOSE");
      Add("save_recalc","ENREGISTRER ET RECALCULER","SAVE AND RECALCULATE");
      Add("apply","APPLIQUER","APPLY");
      Add("tip_reapp_n","Pierres de réévaluation normales","Normal reappraisal stones");
      Add("tip_reapp_a","Pierres de réévaluation antiques","Ancient reappraisal stones");
      Add("tip_refine","Pierres de raffinage","Refinement stones");
      Add("quality_legend","Legendaire","Legendary");
      Add("quality_hero","Heroique","Hero");
      Add("quality_rare","Rare","Rare");
      Add("quality_magic","Magique","Magic");
      Add("rune_normal","Normale","Normal");
      Add("rune_ancient","Antique","Ancient");
      Add("type_gem","Gemme","Gem");
      Add("type_grind","Meule","Grindstone");
      Add("stock_title","Stock des meules et gemmes","Grindstone and gem stock");
      Add("stock_head","STOCK  •  MEULES & GEMMES","STOCK  •  GRINDSTONES & GEMS");
      Add("stock_all_runes","Toutes les runes","All runes");
      Add("stock_normal","Normales","Normal");
      Add("stock_ancient","Antiques","Ancient");
      Add("stock_both","Meules + Gemmes","Grindstones + Gems");
      Add("stock_gems","Gemmes","Gems");
      Add("stock_grinds","Meules","Grindstones");
      Add("stock_set","Nom du set","Set name");
      Add("stock_type","Type","Type");
      Add("stock_stat","Statistique","Stat");
      Add("stock_quality","Qualité","Quality");
      Add("stock_rune","Rune","Rune");
      Add("stock_qty","Quantité","Quantity");
      Add("stock_summary","{0} objets  •  {1} lignes","{0} items  •  {1} rows");
      Add("stock_clear","VIDER  x{0}","CLEAR  x{0}");
      Add("stock_clear_q","Vider les {0} {1} {2} du set {3} ?","Clear {0} {1} {2} from set {3}?");
      Add("stock_clear_t","Confirmer la suppression du stock","Confirm stock deletion");
      Add("stock_cleared","Stock vidé : {0} • {1} • {2} — liste actualisée.","Stock cleared: {0} • {1} • {2} — list updated.");
      Add("retention_title","Seuil de vente","Sell threshold");
      Add("retention_mode","Mode du seuil de vente","Sell threshold mode");
      Add("retention_dyn","Dynamique — nombre de runes","Dynamic — rune count");
      Add("retention_fix","Fixe — score choisi manuellement","Fixed — manual score");
      Add("retention_count","Nombre de runes fortes à conserver","Number of strong runes to keep");
      Add("retention_score","Score minimum à conserver","Minimum score to keep");
      Add("retention_mana","Économie de mana","Mana saver");
      Add("retention_mana_check","Plus strict sur les Pwr up (seuil de vente inchangé)","Stricter Pwr up (sell threshold unchanged)");
      Add("retention_margin","Marge ajoutée au seuil Pwr up","Extra margin on Pwr up threshold");
      Add("retention_fix_info","Toutes les runes avec un score ≥ {0} seront conservées.\r\nEstimation actuelle : {1} runes.","All runes with score ≥ {0} will be kept.\r\nCurrent estimate: {1} runes.");
      Add("retention_dyn_info","Seuil calculé : {0}\r\nIl évoluera automatiquement avec la qualité de ton inventaire.","Calculated threshold: {0}\r\nIt will follow your inventory quality automatically.");
      Add("msg_import_first","Importe d'abord ton JSON Summoners War.","Import your Summoners War JSON first.");
      Add("msg_catalog_missing","Le catalogue des monstres est absent de l'application.","Monster catalog is missing from the app.");
      Add("rta_title","Assistant RTA","RTA advisor");
      Add("rta_win","Assistant Pick / Ban RTA","RTA Pick / Ban Advisor");
      Add("rta_head","RTA  •  ASSISTANT PICK / BAN","RTA  •  PICK / BAN ADVISOR");
      Add("rta_yours","TES PICKS","YOUR PICKS");
      Add("rta_theirs","PICKS ADVERSES","ENEMY PICKS");
      Add("rta_first","J'AI LE 1ER PICK","I HAVE 1ST PICK");
      Add("rta_enemy","L'ENNEMI COMMENCE","ENEMY STARTS");
      Add("rta_new","NOUVEAU DRAFT","NEW DRAFT");
      Add("rta_pool","POOL + BUILDS","POOL + BUILDS");
      Add("rta_reset","RESET RTA","RESET RTA");
      Add("rta_meta","MAJ META","UPDATE META");
      Add("rta_reset_q","Réinitialiser la sélection et les réglages RTA ?","Reset the RTA selection and settings?");
      Add("rta_reset_ok","Réglages et monstres RTA réinitialisés","RTA settings and monsters reset");
      Add("rta_col_mon","Monstre","Monster");
      Add("rta_col_name","Nom","Name");
      Add("rta_col_score","Indice","Score");
      Add("rta_col_why","Pourquoi","Why");
      Add("rta_sort_tip","Clic : du meilleur au pire, reclic pour inverser","Click: best to worst, click again to reverse");
      Add("rta_hint_first","Tes picks du tour se confirment tout seuls. Clique un pick pour l'enlever, ? pour un autre. Place les picks adverses à droite","Your picks for this turn auto-confirm. Click a pick to remove it, ? for another. Place enemy picks on the right");
      Add("rta_hint_enemy","Place le pick adverse avec ?. Ensuite tes picks du tour se confirment tout seuls","Place the enemy pick with ?. Then your picks for the turn auto-confirm");
      Add("rta_load","Chargement des statistiques RTA (LuckSack) saison 38…","Loading RTA stats (LuckSack) season 38…");
      Add("rta_load_live","Mise à jour meta RTA (LuckSack + SWLens)…","Updating RTA meta (LuckSack + SWLens)…");
      Add("rta_load_fail","Données RTA indisponibles : {0}","RTA data unavailable: {0}");
      Add("rta_loaded","{0} • {1} possédés • clique une case ? pour chercher un monstre","{0} • {1} owned • click a ? slot to search a monster");
      Add("rta_loaded_stats","{0} monstres LuckSack S38 • top 300 pick + builds SWLens","{0} LuckSack S38 monsters • top 300 pick + SWLens builds");
      Add("rta_pick_title","Choisir un monstre","Choose a monster");
      Add("rta_pick_mine","Choisir un de tes picks","Choose one of your picks");
      Add("rta_pick_foe","Choisir un pick adverse","Choose an enemy pick");
      Add("rta_pick_hint","  •  clique l'icône : le pick se place tout de suite","  •  click the icon: the pick is placed immediately");
      Add("rta_already","{0} est déjà pick","{0} is already picked");
      Add("rta_phase_idle","Choisis J'AI LE 1ER PICK pour voir le conseil, ou L'ENNEMI COMMENCE puis place son pick","Choose I HAVE 1ST PICK to see the advice, or ENEMY STARTS then place their pick");
      Add("rta_phase_ban","PHASE BAN  •  bannis : {0}","BAN PHASE  •  ban: {0}");
      Add("rta_phase_you_first","TU AS LE 1ER PICK  •  conseil : {0}","YOU HAVE 1ST PICK  •  advice: {0}");
      Add("rta_phase_foe_first","L'ENNEMI A LE 1ER PICK  •  place son pick dans PICKS ADVERSES","ENEMY HAS 1ST PICK  •  place their pick in ENEMY PICKS");
      Add("rta_phase_answer","CONTRE SON PICK  •  tes {0} meilleurs : {1}","VS THEIR PICK  •  your best {0}: {1}");
      Add("rta_phase_wait_two","TU AS LE 1ER PICK  •  attends ses 2 picks, place-les à droite","YOU HAVE 1ST PICK  •  wait for their 2 picks, place them on the right");
      Add("rta_phase_wait","TOUR ADVERSE  •  place ses picks à droite, le conseil sera recalculé après","ENEMY TURN  •  place their picks on the right, advice updates after");
      Add("rta_phase_one","TON PICK  •  pool {0} : {1}","YOUR PICK  •  pool {0}: {1}");
      Add("rta_phase_many","TES {0} PICKS  •  pool {1} : {2}","YOUR {0} PICKS  •  pool {1}: {2}");
      Add("rta_why_glue","Ban le lien de leur équipe • ","Ban their team glue • ");
      Add("rta_why_threat","Menace : ","Threat: ");
      Add("rta_why_ban","ban {0} %, force globale et matchups contre ton équipe","ban {0}%, overall strength and matchups vs your team");
      Add("rta_why_syn","Synergie avec {0}","Synergy with {0}");
      Add("rta_why_vs","Contre les picks adverses • {0} matchup(s) fiable(s)","Vs enemy picks • {0} reliable matchup(s)");
      Add("rta_why_flex","Choix global solide et flexible","Solid, flexible overall pick");
      Add("rta_owned_eq"," (équivalent possédé)"," (owned equivalent)");
      Add("rta_pool_title","Pool RTA • {0} monstres équipés","RTA pool • {0} runed monsters");
      Add("rta_pool_fail","Optimisation RTA impossible : {0}","RTA optimization failed: {0}");
      Add("rta_chg_title","Top {0}  •  changements meta","Top {0}  •  meta changes");
      Add("rta_chg_head","Monstres possédés qui rentrent ou sortent de ton top {0}","Owned monsters entering or leaving your top {0}");
      Add("rta_chg_in","ENTRENT  •  {0}","IN  •  {0}");
      Add("rta_chg_out","SORTENT  •  {0}","OUT  •  {0}");
      Add("rta_chg_none","Aucun","None");
      Add("rta_slot_advice","conseil","advice");
      Add("rta_monster_n","Monstre {0}","Monster {0}");
      Add("rta_pool_col_turn","Tour","Turn");
      Add("rta_pool_col_meta","Meta (LuckSack S38)","Meta (LuckSack S38)");
      Add("rta_pool_col_sets","Sets proposés (SWLens)","Suggested sets (SWLens)");
      Add("rta_pool_col_prio","Priorités SWLens","SWLens priorities");
      Add("rta_pool_col_slot","Slot 2/4/6 SWLens","Slot 2/4/6 SWLens");
      Add("rta_pool_col_ae_main","Artefact Élém. — Stat ppale","Elem. artifact — Main");
      Add("rta_pool_col_ae_sub","Artefact Élém. — Sub stats","Elem. artifact — Sub stats");
      Add("rta_pool_col_at_main","Artefact Type — Stat ppale","Type artifact — Main");
      Add("rta_pool_col_at_sub","Artefact Type — Sub stats","Type artifact — Sub stats");
      Add("rta_pool_col_caps","Plafonds","Caps");
      Add("crash","Une erreur a été interceptée. Le détail a été enregistré dans le journal de l'application.\r\n\r\n{0}","An error was caught. Details were saved to the app log.\r\n\r\n{0}");
      Add("save_settings_fail","Sauvegarde des paramètres impossible : {0}","Could not save settings: {0}");
      Add("save_stock_fail","Sauvegarde du stock impossible : {0}","Could not save stock: {0}");
      Add("save_live_fail","Sauvegarde des changements automatiques impossible : {0}","Could not save live changes: {0}");
      Add("hide_upgrade","Cacher cette rune de ce tri","Hide this rune from this sort");
      Add("hide_upgrade_done","Rune masquée du tri Amélioration Disponible jusqu'au prochain import JSON.","Rune hidden from Available Upgrade sort until the next JSON import.");
      Add("live_stock","Stock gemmes/meules synchronisé en temps réel","Gem/grindstone stock synced live");
      Add("live_reapp","Pierres de réévaluation synchronisées en temps réel","Reappraisal stones synced live");
      Add("live_refine","Pierres de raffinage synchronisées en temps réel","Refinement stones synced live");
      Add("live_grind","Meule appliquée sur la rune {0}","Grindstone applied to rune {0}");
      Add("live_gem","Gemme appliquée sur la rune {0}","Gem applied to rune {0}");
      Add("live_reapp_pick","Choix de réévaluation appliqué à la rune {0}","Reappraisal choice applied to rune {0}");
      Add("live_refine_pick","Choix de raffinage appliqué à la rune {0}","Refinement choice applied to rune {0}");
      Add("live_upgrade","Rune {0} mise à jour en +{1}","Rune {0} updated to +{1}");
      Add("live_hammer","{0} runes mises à jour avec le marteau","{0} runes updated with the hammer");
      Add("live_sold_one","{0} rune vendue retirée","{0} sold rune removed");
      Add("live_sold_many","{0} runes vendues retirées","{0} sold runes removed");
      Add("live_new_rune_one","{0} nouvelle rune ajoutée","{0} new rune added");
      Add("live_new_rune_many","{0} nouvelles runes ajoutées","{0} new runes added");
      Add("gem_max","Gemme max","Max gem");
      Add("quality_violet","Violette","Hero");
      Add("water","Eau","Water");
      Add("fire","Feu","Fire");
      Add("wind","Vent","Wind");
      Add("light","Lumière","Light");
      Add("dark","Ténèbres","Dark");
      Add("reeval_title","Choix de réévaluation","Reappraisal choice");
      Add("refine_title","Choix de raffinage","Refinement choice");
      Add("take_new","PRENDRE LA NOUVELLE","TAKE THE NEW ONE");
      Add("keep_old","GARDER L’ACTUELLE","KEEP THE CURRENT ONE");
      Add("current","ACTUELLE","CURRENT");
      Add("preset_of","Preset : {0}","Preset: {0}");
      Add("before_refine","AVANT RAFFINAGE","BEFORE REFINEMENT");
      Add("after_refine","APRÈS RAFFINAGE","AFTER REFINEMENT");
      Add("chest_title","Choisir 1 rune sur {0}","Pick 1 rune out of {0}");
      Add("chest_head","COFFRE • CHOISIS LA MEILLEURE RUNE","CHEST • PICK THE BEST RUNE");
      Add("take","PRENDRE","TAKE");
      Add("skill_title","Skill-Up 4★","Skill-Up 4★");
      Add("skill_search","Famille ou nom","Family or name");
      Add("skill_families","FAMILLES 4★","4★ FAMILIES");
      Add("skill_fodder","DOUBLONS","FODDER");
      Add("skill_family_hint","Tape une famille : chaque élément 4★, skill-ups manquants.","Type a family: each 4★ element and missing skill-ups.");
      Add("skill_family_sum","{0} familles  •  {1} éléments pas max","{0} families  •  {1} elements not maxed");
      Add("skill_gap_none","Aucun 4★ de famille à afficher.","No 4★ family to show.");
      Add("skill_max","MAX","MAX");
      Add("skill_missing","MANQUE {0}","NEED {0}");
      Add("skill_not_owned","PAS POSSÉDÉ","NOT OWNED");
      Add("skill_elem_gap","{0} pas max","{0} not maxed");
      Add("skill_row_collab","Collab","Collab");
      Add("skill_row_sw","Summoners War","Summoners War");
      Add("coeff_title","Coefficients de calcul","Calculation coefficients");
      Add("coeff_p1","Poids P1","P1 weight");
      Add("coeff_p2","Poids P2","P2 weight");
      Add("coeff_p3","Poids P3","P3 weight");
      Add("coeff_main","Bonus stat principale","Main stat bonus");
      Add("coeff_ok_set","Facteur set acceptable","Accepted set factor");
      Add("coeff_bad_set","Facteur set exclu","Excluded set factor");
      Add("coeff_sim","Seuil Potential simulé +12","Simulated +12 potential threshold");
      Add("coeff_bad","Valeur incorrecte : {0}","Invalid value: {0}");
      Add("presets_saved","Presets enregistrés et scores recalculés.","Presets saved and scores recalculated.");
      Add("coeff_saved","Coefficients enregistrés et scores recalculés.","Coefficients saved and scores recalculated.");
      Add("autokeep_saved","Seuils Auto-Keep enregistrés.","Auto-Keep thresholds saved.");
      Add("spd_title","Classement SPD — Violent / Swift / Will / Despair","SPD ranking — Violent / Swift / Will / Despair");
      Add("lang_saved","Interface : {0}","Interface: {0}");
      Add("lang_fr","Français","French");
      Add("lang_en","English","English");
      Add("lang_label","Langue","Language");
      Add("live_hammer_msg","{0} runes mises à jour avec le marteau","{0} runes updated with the hammer");
      Add("live_new_runes","{0} nouvelle{1} rune{2} ajoutée{2}","{0} new rune{2} added");
      Add("live_stock_short","stock gemmes/meules synchronisé","gem/grindstone stock synced");
      Add("live_reapp_short","pierres de réévaluation synchronisées","reappraisal stones synced");
      Add("live_skill_monsters","Skill-up et stock de monstres mis à jour en temps réel","Skill-up and monster stock updated live");
      Add("live_monster_stock","Stock de monstres mis à jour en temps réel","Monster stock updated live");
      Add("live_summon","{0} invocation{1} ajoutée{1} au calcul Skill-Up","{0} summon{1} added to Skill-Up");
      Add("status_seuil_fix","Seuil fixe appliqué : {0}","Fixed threshold applied: {0}");
      Add("status_seuil_dyn","Seuil dynamique appliqué : {0}","Dynamic threshold applied: {0}");
      Add("status_mana","  •  Économie de mana active (+{0})","  •  Mana saver on (+{0})");
      Add("import_first","Importe d'abord ton JSON Summoners War.","Import your Summoners War JSON first.");
      Add("catalog_missing","Le catalogue des monstres est absent de l'application.","Monster catalog is missing from the app.");
      Add("before","ACTUELLE","CURRENT");
      Add("after","NOUVELLE","NEW");
      Add("keep_current","GARDER L’ACTUELLE","KEEP THE CURRENT ONE");
      Add("take_new","PRENDRE LA NOUVELLE","TAKE THE NEW ONE");
      Add("preset_colon","Preset : {0}","Preset: {0}");
      Add("prio_none","Non","Off");
      Add("explain_none","Aucun preset compatible avec le set et la principale : score 0.","No preset matches this set and main stat: score 0.");
      Add("explain_proj","Projection optimiste à +12 (améliorations maximales possibles).","Optimistic +12 projection (maximum possible upgrades).");
      Add("explain_stat","{0} : ({1} + meule {2}) / {3} × poids effectif {4} = {5}","{0}: ({1} + grind {2}) / {3} × effective weight {4} = {5}");
      Add("explain_gemgain","Gain gemmage théorique : +{0}","Theoretical gem gain: +{0}");
      Add("explain_main","Principale : +{0} ; total pondéré = {1}","Main: +{0}; weighted total = {1}");
      Add("explain_formula","10 × (total / 11)^1,15 × set {0} × preset {1} × SPD {2}","10 × (total / 11)^1.15 × set {0} × preset {1} × SPD {2}");
      Add("explain_raw","Score brut {0} + bonus stock {1} = {2}","Raw score {0} + stock bonus {1} = {2}");
      Add("explain_stock","Bonus stock : (max − stock du slot) / (max − min) ; 0 si tous égaux. Maximum +1, aucun malus d'abondance.","Stock bonus: (max − slot stock) / (max − min); 0 if all equal. Maximum +1, no abundance penalty.");
      Add("explain_rules_hit","Règles déclenchées : {0} — total +{1}","Triggered rules: {0} — total +{1}");
      Add("explain_rules_none","Aucune règle déclenchée.","No rule triggered.");
      Add("explain_weights","Poids : P1={0}, P2={1}, P3={2} ; fixes ×0,55/0,45 ; CR/CD/ACC/RES ×1,3 ; RES Energy/Endure et ACC Seal/Fight/Despair/Focus ×1,15 ; SPD ×1,1 sur toutes les runes ; presets rapides ×1,05.","Weights: P1={0}, P2={1}, P3={2}; flats ×0.55/0.45; CR/CD/ACC/RES ×1.3; RES Energy/Endure and ACC Seal/Fight/Despair/Focus ×1.15; SPD ×1.1 on every rune; fast presets ×1.05.");
      Add("explain_hist","Ajustement historique après amélioration/gemmage : {0} ; score affiché {1}","Historical adjustment after upgrade/gem: {0}; displayed score {1}");
      Add("explain_gem_none","Aucun preset compatible.","No compatible preset.");
      Add("explain_gem_contrib","Contribution source {0} → cible {1} ; gain pondéré +{2}.","Source contribution {0} → target {1}; weighted gain +{2}.");
      Add("explain_gem_how","Choix du plus grand gain pondéré parmi les remplacements autorisés : priorité du preset, principale/innée exclues, pas de doublon, compatibilité du slot, ligne déjà gemmée respectée, % conservé si un fixe remplaçable existe.","Picks the largest weighted gain among allowed replacements: preset priority, main/innate excluded, no duplicate, slot compatibility, already-gemmed line kept, % kept if a replaceable flat exists.");
      Add("explain_gem_stock","Gemme disponible dans le stock compatible (set ou immémorial).","Gem available in compatible stock (set or immemorial).");
      Add("explain_gem_nostock","Aucune gemme améliorante en stock confirmée : cible théorique si proposée.","No confirmed improving gem in stock: theoretical target if shown.");
      Add("explain_gem_plus12","Recommandation sur la projection +12, à revérifier après les améliorations réelles.","Recommendation on the +12 projection; recheck after real upgrades.");
      Add("refine_tip_head","Raffinage : moyenne pondérée des répartitions de rolls. Résultat {0}, gain {1}.\r\nCalcul du potentiel courant ci-dessous :\r\n","Refinement: weighted average of roll splits. Result {0}, gain {1}.\r\nCurrent potential calculation below:\r\n");
      Add("preset_win_title","Presets • valeurs et stock","Presets • values and stock");
      Add("preset_global_col","Valeur globale","Global value");
      Add("preset_sets_pref","Sets préférés","Preferred sets");
      Add("preset_sets_ok","Sets acceptables","Accepted sets");
      Add("preset_global_row","Valeur globale par stat","Global value per stat");
      Add("preset_stock_btn","RÉCAP STOCK / BONUS","STOCK / BONUS SUMMARY");
      Add("presets_globals_saved","Presets et valeurs globales enregistrés.","Presets and global values saved.");
      Add("preset_stock_title","Stock par preset / set / slot — bonus maximum +1 point","Stock by preset / set / slot — max bonus +1");
      Add("autokeep_title","Auto-Keep — seuils par set et par stat","Auto-Keep — thresholds by set and stat");
      Add("autokeep_info","Une rune +12 est gardée (Keep) dès qu'une sous-stat atteint le seuil ci-dessous pour son set, même sous le seuil de vente normal. Laisser vide ou 0 = désactivé pour cette case.","A +12 rune is kept as soon as a substat reaches the threshold below for its set, even under the normal sell threshold. Leave empty or 0 to disable that cell.");
      Add("save","ENREGISTRER","SAVE");
      Add("tip_set_pref","Set préféré — cliquer pour retirer","Preferred set — click to remove");
      Add("tip_set_ok","Set acceptable — cliquer pour retirer","Accepted set — click to remove");
      Add("tip_set_add","Cliquer pour ajouter en {0}","Click to add as {0}");
      Add("tip_set_role_pref","Préféré","Preferred");
      Add("tip_set_role_ok","Acceptable","Accepted");
      Add("explain_head","{0} — {1} / slot {2}","{0} — {1} / slot {2}");
      Add("cancel_btn","ANNULER","CANCEL");
      Add("chest_rank","Classement","Rank");
      Add("chest_subs","Sous-stats","Substats");
      Add("chest_advice","Conseil","Advice");
      Add("skill_hidden_show","AFFICHER LES MONSTRES CACHÉS","SHOW HIDDEN MONSTERS");
      Add("skill_hidden_hide","CACHER LES MONSTRES MASQUÉS","HIDE MASKED MONSTERS");
      Add("skill_protected","Protégés : monstres Light/Dark, natifs 5★ et monstres favoris/verrouillés.","Protected: Light/Dark monsters, native 5★, and locked/favorite monsters.");
      Add("skill_sealed","Stock du Sanctuaire scellé absent de ce JSON : les cibles sont visibles, mais les quantités ×N ne peuvent pas encore être comptées.","Sealed Sanctuary stock missing from this JSON: targets are visible, but ×N quantities cannot be counted yet.");
      Add("skill_summary","{0} monstres affichés  •  {1} skill-ups disponibles  •  {2} caché{3}","{0} monsters shown  •  {1} skill-ups available  •  {2} hidden");
      Add("skill_empty_hidden","Tous les monstres correspondants sont cachés. Utilise le bouton « Afficher les monstres cachés ».","All matching monsters are hidden. Use the Show hidden monsters button.");
      Add("skill_empty_none","Aucun Skill-Up 4★ disponible avec les règles de protection actuelles.","No 4★ Skill-Up available with the current protection rules.");
      Add("skill_analyse_fail","Analyse impossible : {0}","Analysis failed: {0}");
      Add("skill_native","Natif {0}★","Native {0}★");
      Add("skill_usable","{0} skill-up{1} disponible{1}","{0} skill-up{1} available");
      Add("skill_hidden_card","MASQUÉ — CLIC DROIT POUR RÉAFFICHER","HIDDEN — RIGHT-CLICK TO SHOW AGAIN");
      Add("skill_fodder_ok","DOUBLONS UTILISABLES","USABLE FODDER");
      Add("skill_fodder_none","AUCUN DOUBLON DISPONIBLE ACTUELLEMENT","NO FODDER AVAILABLE RIGHT NOW");
      Add("skill_hide","Cacher ce monstre de la page Skill-Up","Hide this monster from the Skill-Up page");
      Add("skill_unhide","Réafficher ce monstre","Show this monster again");
      Add("spd_info","1 ligne par set+slot (meilleure rune du slot) — slots 1, 3, 4, 5, 6. SPD de base hors meule, SPD + meules = base + grind.","1 row per set+slot (best rune on that slot) — slots 1, 3, 4, 5, 6. Base SPD without grind, SPD + grind = base + grindstone.");
      Add("spd_base","SPD de base","Base SPD");
      Add("spd_grind","SPD + meules","SPD + grind");
      Add("spd_reco","Cible refinement recommandée : {0} Slot {1} — {2}★ +{3} — {4}","Recommended refinement target: {0} Slot {1} — {2}★ +{3} — {4}");
      Add("spd_noreco","Aucune cible de refinement valable trouvée (legendaire + SPD réel + hors top 10%).","No valid refinement target found (legendary + real SPD + outside top 10%).");
      Add("spd_subs","Sous-stats de la meilleure rune","Best rune substats");
      Add("spd_none","Aucune rune éligible sur ce slot","No eligible rune on this slot");
      Add("spd_improved_title","Records SPD améliorés","Improved SPD records");
      Add("spd_improved_one","1 SLOT AMÉLIORÉ\nDepuis ta dernière consultation du Classement SPD","1 IMPROVED SLOT\nSince you last opened SPD ranking");
      Add("spd_improved_many","{0} SLOTS AMÉLIORÉS\nDepuis ta dernière consultation du Classement SPD","{0} IMPROVED SLOTS\nSince you last opened SPD ranking");
      Add("spd_old","Ancien SPD","Old SPD");
      Add("spd_new","Nouveau SPD","New SPD");
      Add("tip_paypal","Soutenir le projet via PayPal","Support the project via PayPal");
      Add("tip_discord","Rejoindre le Discord","Join the Discord");
      Add("tip_twitch","Regarder le live Twitch","Watch the Twitch live");
      Add("update_btn","MAJ","UPDATE");
      Add("update_check_btn","VÉRIFIER MAJ","CHECK UPDATE");
      Add("tip_update","Une nouvelle version est disponible","A new version is available");
      Add("tip_update_check","Vérifier si une mise à jour est disponible sur GitHub","Check GitHub for an available update");
      Add("update_ok","Tu es à jour !","You're up to date!");
      Add("update_fail","Impossible de vérifier GitHub. Réessaie plus tard.","Could not check GitHub. Try again later.");
      Add("update_title","Mise à jour disponible","Update available");
      Add("update_head","Version {0} disponible","Version {0} available");
      Add("update_none","Aucune note pour cette version.","No notes for this version.");
      Add("update_download","Télécharger","Download");
      Add("update_applying","Téléchargement...","Downloading...");
      Add("update_dl_fail","Téléchargement de la mise à jour impossible.","Could not download the update.");
      Add("update_later","Plus tard","Later");
      Add("update_status","Nouvelle version {0} disponible","New version {0} available");
      Add("search_hint","ex. Violent slot 1, +12","e.g. Violent slot 1, +12");
      Add("search_tip","Recherche manuelle : set, slot (Violent slot 1) ou niveau d'amélioration (+12).","Manual search: set, slot (Violent slot 1) or upgrade level (+12).");

    }
    static void Add(string key,string fr,string en){Fr[key]=fr;EnMap[key]=en;}
    public static string T(string key){string s;var map=En?EnMap:Fr;return map.TryGetValue(key,out s)?s:key;}
    public static string T(string key,params object[] args){return string.Format(T(key),args);}
    public static string Quality(int grade){return grade>=5?T("quality_legend"):grade==4?T("quality_hero"):grade==3?T("quality_rare"):T("quality_magic");}
    public static string CraftQuality(int grade){return grade>=5?T("quality_legend"):T("quality_violet");}
    public static string Element(string e){if(e=="water")return T("water");if(e=="fire")return T("fire");if(e=="wind")return T("wind");if(e=="light")return T("light");if(e=="dark")return T("dark");return e;}
  }
}
