using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;
using Windows.Foundation;
using Windows.Globalization;
using Windows.Graphics.Imaging;
using Windows.Media.Ocr;
using Windows.Storage.Streams;
using Point=System.Drawing.Point;
using Size=System.Drawing.Size;

namespace RuneManagerModern {
  sealed class CaptureLensResult {
    public Bitmap Image; public RuneRow Rune; public string Text=""; public string Error=""; public bool Complete;
  }

  sealed class CaptureRegionForm:Form {
    Point start,current; bool dragging; Rectangle selected;
    public Rectangle SelectedRegion {get{return selected;}}
    public CaptureRegionForm(){FormBorderStyle=FormBorderStyle.None;Bounds=SystemInformation.VirtualScreen;StartPosition=FormStartPosition.Manual;TopMost=true;ShowInTaskbar=false;BackColor=Color.Black;Opacity=.38;Cursor=Cursors.Cross;DoubleBuffered=true;KeyPreview=true;}
    protected override void OnShown(EventArgs e){base.OnShown(e);Activate();}
    protected override void OnKeyDown(KeyEventArgs e){if(e.KeyCode==Keys.Escape){DialogResult=DialogResult.Cancel;Close();}base.OnKeyDown(e);}
    protected override void OnMouseDown(MouseEventArgs e){if(e.Button!=MouseButtons.Left)return;dragging=true;start=current=e.Location;Invalidate();}
    protected override void OnMouseMove(MouseEventArgs e){if(!dragging)return;current=e.Location;Invalidate();}
    protected override void OnMouseUp(MouseEventArgs e){if(!dragging)return;dragging=false;current=e.Location;selected=Rect(start,current);if(selected.Width<120||selected.Height<100){selected=Rectangle.Empty;Invalidate();return;}selected.Offset(Bounds.Left,Bounds.Top);DialogResult=DialogResult.OK;Close();}
    protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);using(var title=new Font("Segoe UI Semibold",18)){TextRenderer.DrawText(e.Graphics,"Encadre uniquement la fiche de la rune • Échap pour annuler",title,new Rectangle(0,16,Width,50),Color.White,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);}if(!dragging)return;Rectangle r=Rect(start,current);using(var b=new SolidBrush(Color.FromArgb(115,20,184,210)))e.Graphics.FillRectangle(b,r);using(var p=new Pen(Color.FromArgb(34,211,238),3))e.Graphics.DrawRectangle(p,r);}
    static Rectangle Rect(Point a,Point b){return Rectangle.FromLTRB(Math.Min(a.X,b.X),Math.Min(a.Y,b.Y),Math.Max(a.X,b.X),Math.Max(a.Y,b.Y));}
  }

  static class ScreenCaptureLens {
    static readonly object TesseractLock=new object(); static Tesseract.TesseractEngine tesseractEngine;
    static string RegionPath {get{string d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Rune_Manager_Modern");Directory.CreateDirectory(d);return Path.Combine(d,"screen-capture-region.txt");}}
    public static void ResetRegion(){try{if(File.Exists(RegionPath))File.Delete(RegionPath);}catch{}}
    public static bool HasRegion {get{return File.Exists(RegionPath);}}
    public static Rectangle SavedRegion {get{return LoadRegion();}}
    public static Rectangle ChooseRegion(IWin32Window owner){using(var f=new CaptureRegionForm()){if(f.ShowDialog(owner)!=DialogResult.OK)return Rectangle.Empty;Rectangle r=f.SelectedRegion;File.WriteAllText(RegionPath,string.Join(",",new[]{r.X,r.Y,r.Width,r.Height}));return r;}}
    static Rectangle LoadRegion(){try{var p=File.ReadAllText(RegionPath).Split(',').Select(int.Parse).ToArray();if(p.Length==4)return new Rectangle(p[0],p[1],p[2],p[3]);}catch{}return Rectangle.Empty;}
    public static async Task<CaptureLensResult> CaptureAsync(IWin32Window owner,List<RuneRow> account){var result=new CaptureLensResult();Rectangle region=LoadRegion();if(region.IsEmpty)region=ChooseRegion(owner);if(region.IsEmpty){result.Error="Capture annulée.";return result;}try{var screen=SystemInformation.VirtualScreen;if(!screen.Contains(region)){ResetRegion();result.Error="La zone enregistrée n'est plus sur l'écran. Refais le cadrage.";return result;}var bmp=new Bitmap(region.Width,region.Height,PixelFormat.Format32bppArgb);using(var g=Graphics.FromImage(bmp))g.CopyFromScreen(region.Location,Point.Empty,region.Size,CopyPixelOperation.SourceCopy);result.Image=bmp;result.Text=await ReadText(bmp);result.Rune=ParseRune(result.Text);if(result.Rune==null){result.Error="La fiche de rune n'a pas été reconnue. Clic droit sur SCREEN CAPTURE pour refaire le cadrage.";return result;}FinishAnalysis(result,account);return result;}catch(Exception ex){result.Error="Analyse impossible : "+ex.Message;return result;}}
    public static async Task<CaptureLensResult> AnalyzeImageFile(string path,List<RuneRow> account){var result=new CaptureLensResult();try{result.Image=new Bitmap(path);result.Text=await ReadText(result.Image);result.Rune=ParseRune(result.Text);if(result.Rune==null){result.Error="Rune non reconnue.";return result;}FinishAnalysis(result,account);}catch(Exception ex){result.Error=ex.Message;}return result;}
    static int ExpectedSubCount(RuneRow rune){int initial=rune.Grade>=5?4:rune.Grade==4?3:rune.Grade==3?2:1;return Math.Min(4,initial+rune.Level/3);}
    static void FinishAnalysis(CaptureLensResult result,List<RuneRow> account){RuneRow matched=FindAccountRune(result.Rune,account);if(matched!=null)result.Rune=MergeCurrentValues(matched,result.Rune);int expected=ExpectedSubCount(result.Rune);result.Complete=result.Rune.Subs.Count>=expected;var calculation=new List<RuneRow>();if(account!=null)calculation.AddRange(account.Where(x=>!Object.ReferenceEquals(x,matched)));calculation.Add(result.Rune);RuneEngine.Calculate(calculation);}
    static RuneRow FindAccountRune(RuneRow seen,List<RuneRow> account){if(account==null||account.Count==0)return null;var candidates=account.Where(r=>r.Set.Equals(seen.Set,StringComparison.OrdinalIgnoreCase)&&r.Slot==seen.Slot&&r.Main==seen.Main&&seen.Subs.All(s=>r.Subs.Any(x=>x.Stat==s.Stat&&Math.Abs(x.Value-s.Value)<=2))).ToList();return candidates.Count==1?candidates[0]:null;}
    static RuneRow MergeCurrentValues(RuneRow saved,RuneRow seen){var merged=new RuneRow{Id=saved.Id,Set=saved.Set,Slot=saved.Slot,Main=saved.Main,MainValue=seen.MainValue,Innate=saved.Innate,InnateValue=saved.InnateValue,Grade=saved.Grade,Level=seen.Level,Ancient=saved.Ancient,Equipped=saved.Equipped,Marker=saved.Marker,Obtained=saved.Obtained};foreach(var old in saved.Subs){var current=seen.Subs.FirstOrDefault(x=>x.Stat==old.Stat);merged.Subs.Add(new SubStat{Stat=old.Stat,Value=current==null?old.Value:current.Value,Gemmed=old.Gemmed,Grind=old.Grind});}foreach(var current in seen.Subs)if(!merged.Subs.Any(x=>x.Stat==current.Stat)&&merged.Subs.Count<4)merged.Subs.Add(new SubStat{Stat=current.Stat,Value=current.Value});return merged;}
    static async Task<string> ReadText(Bitmap bmp){string tess=ReadTesseract(bmp,Tesseract.PageSegMode.Auto);var first=ParseRune(tess);if(first!=null&&first.Subs.Count>=ExpectedSubCount(first))return tess;var samples=new List<string>();if(tess.Length>0)samples.Add(tess);samples.Add(await ReadTextSingle(bmp));foreach(int threshold in new[]{70,105,140})using(var prepared=PrepareForOcr(bmp,threshold)){samples.Add(await ReadTextSingle(prepared));tess=ReadTesseract(prepared,Tesseract.PageSegMode.Auto);if(tess.Length>0)samples.Add(tess);}using(var left=CropTextArea(bmp)){samples.Add(await ReadTextSingle(left));tess=ReadTesseract(left,Tesseract.PageSegMode.Auto);if(tess.Length>0)samples.Add(tess);foreach(int threshold in new[]{55,80,105,130,155})using(var prepared=PrepareForOcr(left,threshold)){samples.Add(await ReadTextSingle(prepared));tess=ReadTesseract(prepared,Tesseract.PageSegMode.Auto);if(tess.Length>0)samples.Add(tess);}}string best=samples.OrderByDescending(OcrQuality).FirstOrDefault()??"";var parsed=ParseRune(best);if(parsed!=null&&parsed.Subs.Count<4){var extra=new List<string>();foreach(double top in new[]{.17,.38,.46,.54,.62,.70})using(var band=CropBand(bmp,top,.13))using(var prepared=PrepareForOcr(band,90)){extra.Add(await ReadTextSingle(prepared));tess=ReadTesseract(prepared,Tesseract.PageSegMode.SingleLine);if(tess.Length>0)extra.Add(tess);}best+="\nOCR_EXTRA\n"+string.Join("\n",extra);}return best;}
    static string ReadTesseract(Bitmap bitmap,Tesseract.PageSegMode mode){try{lock(TesseractLock){if(tesseractEngine==null){string data=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"tessdata");if(!File.Exists(Path.Combine(data,"eng.traineddata")))return "";tesseractEngine=new Tesseract.TesseractEngine(data,"eng",Tesseract.EngineMode.Default);}byte[] bytes;using(var memory=new MemoryStream()){bitmap.Save(memory,ImageFormat.Png);bytes=memory.ToArray();}using(var pix=Tesseract.Pix.LoadFromMemory(bytes))using(var page=tesseractEngine.Process(pix,mode))return page.GetText()??"";}}catch{return "";}}
    static int OcrQuality(string text){var rune=ParseRune(text);if(rune==null)return 0;return 100+rune.Subs.Count*20+(rune.Main.Length>0?10:0)+Math.Min(20,text.Length/30);}
    static Bitmap PrepareForOcr(Bitmap source,int threshold){var scaled=new Bitmap(Math.Max(1,source.Width*3),Math.Max(1,source.Height*3),PixelFormat.Format32bppArgb);using(var g=Graphics.FromImage(scaled)){g.InterpolationMode=InterpolationMode.HighQualityBicubic;g.DrawImage(source,new Rectangle(0,0,scaled.Width,scaled.Height));}var area=new Rectangle(0,0,scaled.Width,scaled.Height);var data=scaled.LockBits(area,ImageLockMode.ReadWrite,PixelFormat.Format32bppArgb);int size=Math.Abs(data.Stride)*data.Height;var pixels=new byte[size];Marshal.Copy(data.Scan0,pixels,0,size);for(int y=0;y<data.Height;y++){int row=y*Math.Abs(data.Stride);for(int x=0;x<data.Width;x++){int i=row+x*4;int light=(pixels[i]*29+pixels[i+1]*150+pixels[i+2]*77)>>8;byte v=light>=threshold?(byte)0:(byte)255;pixels[i]=pixels[i+1]=pixels[i+2]=v;pixels[i+3]=255;}}Marshal.Copy(pixels,0,data.Scan0,size);scaled.UnlockBits(data);return scaled;}
    static Bitmap CropTextArea(Bitmap source){int width=Math.Max(1,(int)(source.Width*.66));var crop=new Bitmap(width,source.Height,PixelFormat.Format32bppArgb);using(var g=Graphics.FromImage(crop))g.DrawImage(source,new Rectangle(0,0,width,source.Height),new Rectangle(0,0,width,source.Height),GraphicsUnit.Pixel);return crop;}
    static Bitmap CropBand(Bitmap source,double top,double height){int x=0,y=Math.Max(0,(int)(source.Height*top)),width=Math.Max(1,(int)(source.Width*.70)),h=Math.Max(12,Math.Min(source.Height-y,(int)(source.Height*height)));var crop=new Bitmap(width,h,PixelFormat.Format32bppArgb);using(var g=Graphics.FromImage(crop))g.DrawImage(source,new Rectangle(0,0,width,h),new Rectangle(x,y,width,h),GraphicsUnit.Pixel);return crop;}
    static async Task<string> ReadTextSingle(Bitmap bmp){byte[] bytes;using(var memory=new MemoryStream()){bmp.Save(memory,ImageFormat.Png);bytes=memory.ToArray();}var random=new InMemoryRandomAccessStream();var writer=new DataWriter(random);writer.WriteBytes(bytes);await AwaitOperation<uint>(writer.StoreAsync());await AwaitOperation(writer.FlushAsync());writer.DetachStream();random.Seek(0);var decoder=await AwaitOperation(BitmapDecoder.CreateAsync(random));var software=await AwaitOperation(decoder.GetSoftwareBitmapAsync(BitmapPixelFormat.Bgra8,BitmapAlphaMode.Premultiplied));var engine=OcrEngine.TryCreateFromLanguage(new Language("en-US"))??OcrEngine.TryCreateFromUserProfileLanguages();if(engine==null)throw new InvalidOperationException("La reconnaissance de texte anglaise de Windows n'est pas installée.");var read=await AwaitOperation(engine.RecognizeAsync(software));return read.Text??"";}
    static Task<T> AwaitOperation<T>(IAsyncOperation<T> operation){var done=new TaskCompletionSource<T>();operation.Completed=(op,status)=>{try{if(status==AsyncStatus.Completed)done.TrySetResult(op.GetResults());else if(status==AsyncStatus.Canceled)done.TrySetCanceled();else done.TrySetException(op.ErrorCode??new InvalidOperationException("Opération Windows interrompue."));}catch(Exception ex){done.TrySetException(ex);}};return done.Task;}
    static RuneRow ParseRune(string text){
      if(string.IsNullOrWhiteSpace(text))return null;
      string clean=text.Replace('\r','\n');
      clean=Regex.Replace(clean,@"(?<!\d)(\d{1,2})0\s*/\s*0\b","$1%",RegexOptions.IgnoreCase);
      clean=Regex.Replace(clean,@"(?<!\d)\d+[A-Za-z]\b"," ",RegexOptions.IgnoreCase);
      var title=Regex.Match(clean,@"(?i)(?:\+\s*(\d{1,2})\s*)?([A-Za-z]+)(?:\s+Ancient)?\s+Rune\s*[\(\[]\s*([1-6])\s*[\)\]]");
      if(!title.Success)return null;
      int level=0;if(title.Groups[1].Success)int.TryParse(title.Groups[1].Value,out level);
      var rune=new RuneRow{Set=FixSet(title.Groups[2].Value),Slot=int.Parse(title.Groups[3].Value),Grade=4,Level=Math.Max(0,Math.Min(15,level)),Ancient=title.Value.IndexOf("Ancient",StringComparison.OrdinalIgnoreCase)>=0};
      string beforeTitle=clean.Substring(0,title.Index);bool hasInnateTitle=Regex.IsMatch(beforeTitle,@"(?i)[A-Za-z]+\s*$");
      if(Regex.IsMatch(clean,@"\bLeg(?:end(?:ary)?|endaire|enc|encl)\b",RegexOptions.IgnoreCase))rune.Grade=5;else if(Regex.IsMatch(clean,@"\bRare\b",RegexOptions.IgnoreCase))rune.Grade=3;else if(Regex.IsMatch(clean,@"\bMagic\b",RegexOptions.IgnoreCase))rune.Grade=2;
      string statsText=clean.Substring(title.Index+title.Length),extra="";int extraAt=statsText.IndexOf("OCR_EXTRA",StringComparison.Ordinal);
      if(extraAt>=0){extra=statsText.Substring(extraAt+9);statsText=statsText.Substring(0,extraAt);}
      var setBonus=Regex.Match(statsText,@"(?i)\b[24]\s*Set\s*:");if(setBonus.Success)statsText=statsText.Substring(0,setBonus.Index);statsText+="\n"+extra;
      var matches=Regex.Matches(statsText,@"(?im)\b(HP|ATK|DEF|SPD|CRI\s*Rate|CRI\s*Dmg|Resistance|Accuracy)\s*\+?\s*(\d+)(?![\dA-Za-z])\s*(%)?");
      foreach(Match m in matches){string stat=MapStat(m.Groups[1].Value,m.Groups[3].Success);double value=double.Parse(m.Groups[2].Value);if(rune.Main.Length==0){rune.Main=stat;rune.MainValue=value;}else if(hasInnateTitle&&rune.Innate.Length==0){rune.Innate=stat;rune.InnateValue=value;}else{var existing=rune.Subs.FirstOrDefault(x=>x.Stat==stat);if(existing!=null)existing.Value=Math.Max(existing.Value,value);else if(stat!=rune.Main&&rune.Subs.Count<4)rune.Subs.Add(new SubStat{Stat=stat,Value=value});}}
       if(rune.Main.Length==0||rune.Subs.Count==0||!ValidMain(rune.Slot,rune.Main)||rune.Subs.Any(x=>!ValidSub(x)))return null;return rune;
     }
    static bool ValidMain(int slot,string stat){if(slot==1)return stat=="Atk+";if(slot==3)return stat=="Def+";if(slot==5)return stat=="HP+";if(slot==2)return stat=="Spd"||stat=="HP%"||stat=="Atk%"||stat=="Def%";if(slot==4)return stat=="HP%"||stat=="Atk%"||stat=="Def%"||stat=="CtR%"||stat=="CtD%";if(slot==6)return stat=="HP%"||stat=="Atk%"||stat=="Def%"||stat=="Res%"||stat=="Acc%";return false;}
    static bool ValidSub(SubStat stat){if(stat.Value<=0)return false;if(stat.Stat=="HP+")return stat.Value<=3000;if(stat.Stat=="Atk+"||stat.Stat=="Def+")return stat.Value<=300;if(stat.Stat=="Spd")return stat.Value<=45;return stat.Value<=50;}
    static string FixSet(string value){string s=value.Trim();return char.ToUpperInvariant(s[0])+s.Substring(1).ToLowerInvariant();}
    static string MapStat(string raw,bool percent){string s=Regex.Replace(raw,"\\s+","").ToUpperInvariant();if(s=="SPD")return "Spd";if(s=="CRIRATE")return "CtR%";if(s=="CRIDMG")return "CtD%";if(s=="RESISTANCE")return "Res%";if(s=="ACCURACY")return "Acc%";if(s=="ATK")return percent?"Atk%":"Atk+";if(s=="DEF")return percent?"Def%":"Def+";return percent?"HP%":"HP+";}
  }

  sealed class CaptureResultForm:Form {
    public CaptureResultForm(CaptureLensResult result,Icon icon){Text="Screen Capture";Icon=icon;StartPosition=FormStartPosition.CenterScreen;TopMost=true;Size=new Size(650,430);BackColor=Color.FromArgb(7,13,22);ForeColor=Color.White;Font=new Font("Segoe UI",10);var r=result.Rune;var title=new Label{Text=r.Set+" • Slot "+r.Slot+" • "+r.Main+" +"+r.MainValue.ToString("0")+(r.Main.EndsWith("%")?"%":""),Location=new Point(24,20),AutoSize=true,Font=new Font("Segoe UI Semibold",17),ForeColor=Color.FromArgb(20,210,195)};Controls.Add(title);var score=new Label{Text="POTENTIAL VALUE  "+r.Potential.ToString("0.000"),Location=new Point(24,65),AutoSize=true,Font=new Font("Segoe UI Semibold",24),ForeColor=Color.FromArgb(116,235,184)};Controls.Add(score);var details=new Label{Text=string.Join("   ",r.Subs.Select(x=>x.BaseDisplay))+"\n\nAction : "+r.Action+"\nMeilleur preset : "+r.BestBuild+"\nRecommandation : "+r.Recommendation,Location=new Point(26,120),Size=new Size(590,130),Font=new Font("Segoe UI",12),ForeColor=Color.White};Controls.Add(details);var preview=new PictureBox{Image=result.Image,SizeMode=PictureBoxSizeMode.Zoom,Location=new Point(26,260),Size=new Size(590,115),BorderStyle=BorderStyle.FixedSingle};Controls.Add(preview);FormClosed+=(s,e)=>{if(preview.Image!=null)preview.Image.Dispose();};}
  }

  sealed class LiveCaptureForm:Form {
    [DllImport("user32.dll")]static extern bool SetWindowDisplayAffinity(IntPtr hWnd,uint affinity);
    readonly List<RuneRow> account; readonly Timer timer=new Timer(); readonly Label runeName=new Label(),score=new Label(),actionLabel=new Label(),details=new Label(),state=new Label(); bool busy; string lastSignature="";
    public RuneRow LastRune {get;private set;}
    public LiveCaptureForm(CaptureLensResult first,List<RuneRow> runes,Icon icon){account=runes??new List<RuneRow>();Text="Screen Capture • Temps réel";Icon=icon;TopMost=true;ShowInTaskbar=true;FormBorderStyle=FormBorderStyle.FixedToolWindow;MaximizeBox=false;MinimizeBox=false;Size=new Size(455,290);BackColor=Color.FromArgb(7,13,22);ForeColor=Color.White;Font=new Font("Segoe UI",10);PlaceOutsideCapture();runeName.SetBounds(20,16,405,30);runeName.Font=new Font("Segoe UI Semibold",15);runeName.ForeColor=Color.FromArgb(20,210,195);Controls.Add(runeName);score.SetBounds(20,50,405,42);score.Font=new Font("Segoe UI Semibold",23);score.ForeColor=Color.FromArgb(116,235,184);Controls.Add(score);actionLabel.SetBounds(20,94,405,38);actionLabel.Font=new Font("Segoe UI Black",18);Controls.Add(actionLabel);details.SetBounds(20,137,410,72);details.Font=new Font("Segoe UI",10);details.ForeColor=Color.White;Controls.Add(details);state.SetBounds(20,218,250,26);state.Text="● CAPTURE EN TEMPS RÉEL";state.ForeColor=Color.FromArgb(45,220,130);state.Font=new Font("Segoe UI Semibold",9);Controls.Add(state);var stop=new Button{Text="ARRÊTER",Location=new Point(305,214),Size=new Size(120,34),FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(170,45,60),ForeColor=Color.White,Font=new Font("Segoe UI Semibold",9),Cursor=Cursors.Hand};stop.Click+=(s,e)=>Close();Controls.Add(stop);timer.Interval=1100;timer.Tick+=async(s,e)=>await Scan();Shown+=(s,e)=>{try{SetWindowDisplayAffinity(Handle,0x11);}catch{}timer.Start();};FormClosed+=(s,e)=>timer.Stop();Apply(first);}
    void PlaceOutsideCapture(){Rectangle capture=ScreenCaptureLens.SavedRegion,screen=SystemInformation.VirtualScreen;int x,y;if(!capture.IsEmpty&&capture.Bottom+Height+8<=screen.Bottom){x=Math.Max(screen.Left,Math.Min(capture.Right-Width,screen.Right-Width));y=capture.Bottom+8;}else if(!capture.IsEmpty&&capture.Left-Width-8>=screen.Left){x=capture.Left-Width-8;y=Math.Max(screen.Top,Math.Min(capture.Top,screen.Bottom-Height));}else{x=screen.Left+20;y=screen.Top+20;}StartPosition=FormStartPosition.Manual;Location=new Point(x,y);}
    async Task Scan(){if(busy)return;busy=true;try{var result=await ScreenCaptureLens.CaptureAsync(null,account);if(result.Rune!=null&&result.Complete)Apply(result);else{state.Text="● LECTURE REJETÉE — NOUVEL ESSAI…";state.ForeColor=Color.FromArgb(255,176,55);if(result.Image!=null)result.Image.Dispose();}}finally{busy=false;}}
    void Apply(CaptureLensResult result){var r=result.Rune;if(r==null)return;string signature=result.Complete+"|"+r.Id+"|"+r.Set+"|"+r.Slot+"|"+r.Main+"|"+r.Grade+"|"+r.Level+"|"+r.Potential+"|"+string.Join(";",r.Subs.Select(x=>x.Stat+":"+x.Value));if(signature==lastSignature){if(result.Image!=null)result.Image.Dispose();return;}lastSignature=signature;LastRune=r;runeName.Text=r.Set+" • Slot "+r.Slot+" • "+r.Quality+" • "+r.Main+" +"+r.MainValue.ToString("0")+(r.Main.EndsWith("%")?"%":"");score.Text="POTENTIAL  "+r.Potential.ToString("0.000");actionLabel.Text=result.Complete?"ACTION : "+r.Action.ToUpperInvariant():"ACTION : LECTURE INCOMPLÈTE";actionLabel.ForeColor=!result.Complete?Color.FromArgb(255,176,55):r.Action=="Sell"?Color.FromArgb(255,72,84):r.Action=="Pwr up"?Color.FromArgb(45,225,125):Color.FromArgb(34,211,238);string innate=r.Innate.Length>0?"     Innate : "+r.Innate+" +"+r.InnateValue.ToString("0")+(r.Innate.EndsWith("%")?"%":""):"";details.Text="Preset : "+r.BestBuild+innate+"\n"+string.Join("   ",r.Subs.Select(x=>x.BaseDisplay))+"\nRecommandation : "+r.Recommendation;state.Text=result.Complete?"● MÊME CALCUL QUE L'APPLICATION":"● SOUS-STATS INCOMPLÈTES — NOUVELLE LECTURE…";state.ForeColor=result.Complete?Color.FromArgb(45,220,130):Color.FromArgb(255,176,55);if(result.Image!=null)result.Image.Dispose();}
  }
}
